//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-04/12/2007 12:08 AM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.24 at 01:25:15 PM PDT 
//


package com.sun.enterprise.config.serverbeans;

import org.jvnet.hk2.config.Attribute;
import org.jvnet.hk2.config.Configured;
import org.jvnet.hk2.config.Element;

import java.beans.PropertyVetoException;
import java.beans.VetoableChangeListener;
import java.beans.VetoableChangeSupport;
import java.io.Serializable;


/**
 *
 */

/* @XmlType(name = "", propOrder = {
    "listenerConfig",
    "filterConfig"
}) */
@Configured
public class AlertSubscription
        implements Serializable {

	final transient private VetoableChangeSupport support = new VetoableChangeSupport(this);

    private final static long serialVersionUID = 1L;
    @Attribute(required = true)

    protected String name;
    @Element(required=true)
    protected ListenerConfig listenerConfig;
    @Element
    protected FilterConfig filterConfig;



    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
        try {
            support.fireVetoableChange("name", this.name, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.name = value;
    }

    /**
     * Gets the value of the listenerConfig property.
     *
     * @return possible object is
     *         {@link ListenerConfig }
     */
    public ListenerConfig getListenerConfig() {
        return listenerConfig;
    }

    /**
     * Sets the value of the listenerConfig property.
     *
     * @param value allowed object is
     *              {@link ListenerConfig }
     */
    public void setListenerConfig(ListenerConfig value) {
        try {
            support.fireVetoableChange("listenerConfig", this.listenerConfig, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.listenerConfig = value;
    }

    /**
     * Gets the value of the filterConfig property.
     *
     * @return possible object is
     *         {@link FilterConfig }
     */
    public FilterConfig getFilterConfig() {
        return filterConfig;
    }

    /**
     * Sets the value of the filterConfig property.
     *
     * @param value allowed object is
     *              {@link FilterConfig }
     */
    public void setFilterConfig(FilterConfig value) {
        try {
            support.fireVetoableChange("filterConfig", this.filterConfig, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.filterConfig = value;
    }

    public void addVetoableChangeListener(VetoableChangeListener param0) {
        support.addVetoableChangeListener(param0);
    }

    public void addVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.addVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.removeVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(VetoableChangeListener param0) {
        support.removeVetoableChangeListener(param0);
    }

}
