//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-04/12/2007 12:08 AM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.24 at 01:25:15 PM PDT 
//


package com.sun.enterprise.config.serverbeans;

import org.jvnet.hk2.config.Attribute;
import org.jvnet.hk2.config.Configured;
import org.jvnet.hk2.config.Element;

import java.beans.PropertyVetoException;
import java.beans.VetoableChangeListener;
import java.beans.VetoableChangeSupport;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 *
 */

/* @XmlType(name = "", propOrder = {
    "webContainerAvailability",
    "ejbContainerAvailability",
    "jmsAvailability",
    "property"
}) */
@Configured
public class AvailabilityService
        implements Serializable {

	final transient private VetoableChangeSupport support = new VetoableChangeSupport(this);

    private final static long serialVersionUID = 1L;
    @Attribute

    protected String availabilityEnabled;
    @Attribute

    protected String haAgentHosts;
    @Attribute

    protected String haAgentPort;
    @Attribute

    protected String haAgentPassword;
    @Attribute

    protected String haStoreName;
    @Attribute

    protected String autoManageHaStore;
    @Attribute

    protected String storePoolName;
    @Attribute

    protected String haStoreHealthcheckEnabled;
    @Attribute

    protected String haStoreHealthcheckIntervalInSeconds;
    @Element
    protected WebContainerAvailability webContainerAvailability;
    @Element
    protected EjbContainerAvailability ejbContainerAvailability;
    @Element
    protected JmsAvailability jmsAvailability;
    protected List<Property> property = new ConstrainedList<Property>("property", support);



    /**
     * Gets the value of the availabilityEnabled property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getAvailabilityEnabled() {
        if (availabilityEnabled == null) {
            return "true";
        } else {
            return availabilityEnabled;
        }
    }

    /**
     * Sets the value of the availabilityEnabled property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAvailabilityEnabled(String value) {
        try {
            support.fireVetoableChange("availabilityEnabled", this.availabilityEnabled, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.availabilityEnabled = value;
    }

    /**
     * Gets the value of the haAgentHosts property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getHaAgentHosts() {
        return haAgentHosts;
    }

    /**
     * Sets the value of the haAgentHosts property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setHaAgentHosts(String value) {
        try {
            support.fireVetoableChange("haAgentHosts", this.haAgentHosts, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.haAgentHosts = value;
    }

    /**
     * Gets the value of the haAgentPort property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getHaAgentPort() {
        return haAgentPort;
    }

    /**
     * Sets the value of the haAgentPort property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setHaAgentPort(String value) {
        try {
            support.fireVetoableChange("haAgentPort", this.haAgentPort, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.haAgentPort = value;
    }

    /**
     * Gets the value of the haAgentPassword property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getHaAgentPassword() {
        return haAgentPassword;
    }

    /**
     * Sets the value of the haAgentPassword property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setHaAgentPassword(String value) {
        try {
            support.fireVetoableChange("haAgentPassword", this.haAgentPassword, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.haAgentPassword = value;
    }

    /**
     * Gets the value of the haStoreName property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getHaStoreName() {
        return haStoreName;
    }

    /**
     * Sets the value of the haStoreName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setHaStoreName(String value) {
        try {
            support.fireVetoableChange("haStoreName", this.haStoreName, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.haStoreName = value;
    }

    /**
     * Gets the value of the autoManageHaStore property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getAutoManageHaStore() {
        if (autoManageHaStore == null) {
            return "false";
        } else {
            return autoManageHaStore;
        }
    }

    /**
     * Sets the value of the autoManageHaStore property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAutoManageHaStore(String value) {
        try {
            support.fireVetoableChange("autoManageHaStore", this.autoManageHaStore, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.autoManageHaStore = value;
    }

    /**
     * Gets the value of the storePoolName property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getStorePoolName() {
        return storePoolName;
    }

    /**
     * Sets the value of the storePoolName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setStorePoolName(String value) {
        try {
            support.fireVetoableChange("storePoolName", this.storePoolName, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.storePoolName = value;
    }

    /**
     * Gets the value of the haStoreHealthcheckEnabled property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getHaStoreHealthcheckEnabled() {
        if (haStoreHealthcheckEnabled == null) {
            return "false";
        } else {
            return haStoreHealthcheckEnabled;
        }
    }

    /**
     * Sets the value of the haStoreHealthcheckEnabled property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setHaStoreHealthcheckEnabled(String value) {
        try {
            support.fireVetoableChange("haStoreHealthcheckEnabled", this.haStoreHealthcheckEnabled, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.haStoreHealthcheckEnabled = value;
    }

    /**
     * Gets the value of the haStoreHealthcheckIntervalInSeconds property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getHaStoreHealthcheckIntervalInSeconds() {
        if (haStoreHealthcheckIntervalInSeconds == null) {
            return "5";
        } else {
            return haStoreHealthcheckIntervalInSeconds;
        }
    }

    /**
     * Sets the value of the haStoreHealthcheckIntervalInSeconds property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setHaStoreHealthcheckIntervalInSeconds(String value) {
        try {
            support.fireVetoableChange("haStoreHealthcheckIntervalInSeconds", this.haStoreHealthcheckIntervalInSeconds, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.haStoreHealthcheckIntervalInSeconds = value;
    }

    /**
     * Gets the value of the webContainerAvailability property.
     *
     * @return possible object is
     *         {@link WebContainerAvailability }
     */
    public WebContainerAvailability getWebContainerAvailability() {
        return webContainerAvailability;
    }

    /**
     * Sets the value of the webContainerAvailability property.
     *
     * @param value allowed object is
     *              {@link WebContainerAvailability }
     */
    public void setWebContainerAvailability(WebContainerAvailability value) {
        try {
            support.fireVetoableChange("webContainerAvailability", this.webContainerAvailability, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.webContainerAvailability = value;
    }

    /**
     * Gets the value of the ejbContainerAvailability property.
     *
     * @return possible object is
     *         {@link EjbContainerAvailability }
     */
    public EjbContainerAvailability getEjbContainerAvailability() {
        return ejbContainerAvailability;
    }

    /**
     * Sets the value of the ejbContainerAvailability property.
     *
     * @param value allowed object is
     *              {@link EjbContainerAvailability }
     */
    public void setEjbContainerAvailability(EjbContainerAvailability value) {
        try {
            support.fireVetoableChange("ejbContainerAvailability", this.ejbContainerAvailability, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.ejbContainerAvailability = value;
    }

    /**
     * Gets the value of the jmsAvailability property.
     *
     * @return possible object is
     *         {@link JmsAvailability }
     */
    public JmsAvailability getJmsAvailability() {
        return jmsAvailability;
    }

    /**
     * Sets the value of the jmsAvailability property.
     *
     * @param value allowed object is
     *              {@link JmsAvailability }
     */
    public void setJmsAvailability(JmsAvailability value) {
        try {
            support.fireVetoableChange("jmsAvailability", this.jmsAvailability, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.jmsAvailability = value;
    }

    /**
     * Gets the value of the property property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the property property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProperty().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link Property }
     */
    public List<Property> getProperty() {
        return this.property;
    }

    public void addVetoableChangeListener(VetoableChangeListener param0) {
        support.addVetoableChangeListener(param0);
    }

    public void addVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.addVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.removeVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(VetoableChangeListener param0) {
        support.removeVetoableChangeListener(param0);
    }

}
