//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-04/12/2007 12:08 AM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.24 at 01:25:15 PM PDT 
//


package com.sun.enterprise.config.serverbeans;

import org.jvnet.hk2.config.Attribute;
import org.jvnet.hk2.config.Configured;
import org.jvnet.hk2.config.Element;

import java.beans.PropertyVetoException;
import java.beans.VetoableChangeListener;
import java.beans.VetoableChangeSupport;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 *
 */

/* @XmlType(name = "", propOrder = {
    "serverRef",
    "resourceRef",
    "applicationRef",
    "systemProperty",
    "property"
}) */
@Configured
public class Cluster
        implements Serializable {

	final transient private VetoableChangeSupport support = new VetoableChangeSupport(this);

    private final static long serialVersionUID = 1L;
    @Attribute(required = true)

    protected String name;
    @Attribute(required = true)

    protected String configRef;
    @Attribute

    protected String heartbeatEnabled;
    @Attribute

    protected String heartbeatPort;
    @Attribute

    protected String heartbeatAddress;
    @Element
    protected List<ServerRef> serverRef = new ConstrainedList<ServerRef>("serverRef", support);
    @Element
    protected List<ResourceRef> resourceRef = new ConstrainedList<ResourceRef>("resourceRef", support);
    @Element
    protected List<ApplicationRef> applicationRef = new ConstrainedList<ApplicationRef>("applicationRef", support);
    @Element
    protected List<SystemProperty> systemProperty = new ConstrainedList<SystemProperty>("systemProperty", support);
    protected List<Property> property = new ConstrainedList<Property>("property", support);

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
        try {
            support.fireVetoableChange("name", this.name, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.name = value;
    }

    /**
     * Gets the value of the configRef property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getConfigRef() {
        return configRef;
    }

    /**
     * Sets the value of the configRef property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setConfigRef(String value) {
        try {
            support.fireVetoableChange("configRef", this.configRef, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.configRef = value;
    }

    /**
     * Gets the value of the heartbeatEnabled property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getHeartbeatEnabled() {
        if (heartbeatEnabled == null) {
            return "true";
        } else {
            return heartbeatEnabled;
        }
    }

    /**
     * Sets the value of the heartbeatEnabled property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setHeartbeatEnabled(String value) {
        try {
            support.fireVetoableChange("heartbeatEnabled", this.heartbeatEnabled, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.heartbeatEnabled = value;
    }

    /**
     * Gets the value of the heartbeatPort property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getHeartbeatPort() {
        return heartbeatPort;
    }

    /**
     * Sets the value of the heartbeatPort property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setHeartbeatPort(String value) {
        try {
            support.fireVetoableChange("heartbeatPort", this.heartbeatPort, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.heartbeatPort = value;
    }

    /**
     * Gets the value of the heartbeatAddress property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getHeartbeatAddress() {
        return heartbeatAddress;
    }

    /**
     * Sets the value of the heartbeatAddress property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setHeartbeatAddress(String value) {
        try {
            support.fireVetoableChange("heartbeatAddress", this.heartbeatAddress, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.heartbeatAddress = value;
    }

    /**
     * Gets the value of the serverRef property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the serverRef property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getServerRef().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link ServerRef }
     */
    public List<ServerRef> getServerRef() {
        return this.serverRef;
    }

    /**
     * Gets the value of the resourceRef property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the resourceRef property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResourceRef().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link ResourceRef }
     */
    public List<ResourceRef> getResourceRef() {
        return this.resourceRef;
    }

    /**
     * Gets the value of the applicationRef property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the applicationRef property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getApplicationRef().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link ApplicationRef }
     */
    public List<ApplicationRef> getApplicationRef() {
        return this.applicationRef;
    }

    /**
     * Gets the value of the systemProperty property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the systemProperty property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSystemProperty().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link SystemProperty }
     */
    public List<SystemProperty> getSystemProperty() {
        return this.systemProperty;
    }

    /**
     * Gets the value of the property property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the property property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProperty().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link Property }
     */
    public List<Property> getProperty() {
        return this.property;
    }

    public void addVetoableChangeListener(VetoableChangeListener param0) {
        support.addVetoableChangeListener(param0);
    }

    public void addVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.addVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.removeVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(VetoableChangeListener param0) {
        support.removeVetoableChangeListener(param0);
    }

}
