//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-04/12/2007 12:08 AM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.24 at 01:25:15 PM PDT 
//


package com.sun.enterprise.config.serverbeans;

import org.jvnet.hk2.config.Attribute;
import org.jvnet.hk2.config.Configured;
import org.jvnet.hk2.config.Element;

import java.beans.PropertyVetoException;
import java.beans.VetoableChangeListener;
import java.beans.VetoableChangeSupport;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 *
 */

/* @XmlType(name = "", propOrder = {
    "httpService",
    "iiopService",
    "adminService",
    "connectorService",
    "webContainer",
    "ejbContainer",
    "mdbContainer",
    "jmsService",
    "logService",
    "securityService",
    "transactionService",
    "monitoringService",
    "diagnosticService",
    "javaConfig",
    "availabilityService",
    "threadPools",
    "alertService",
    "groupManagementService",
    "managementRules",
    "systemProperty",
    "property"
}) */
@Configured
public class Config
        implements Serializable {

	final transient private VetoableChangeSupport support = new VetoableChangeSupport(this);

    private final static long serialVersionUID = 1L;
    @Attribute(required = true)

    protected String name;
    @Attribute

    protected String dynamicReconfigurationEnabled;
    @Element(required=true)
    protected HttpService httpService;
    @Element(required=true)
    protected IiopService iiopService;
    @Element(required=true)
    protected AdminService adminService;
    @Element
    protected ConnectorService connectorService;
    @Element(required=true)
    protected WebContainer webContainer;
    @Element(required=true)
    protected EjbContainer ejbContainer;
    @Element(required=true)
    protected MdbContainer mdbContainer;
    @Element
    protected JmsService jmsService;
    @Element(required=true)
    protected LogService logService;
    @Element(required=true)
    protected SecurityService securityService;
    @Element(required=true)
    protected TransactionService transactionService;
    @Element(required=true)
    protected MonitoringService monitoringService;
    @Element
    protected DiagnosticService diagnosticService;
    @Element(required=true)
    protected JavaConfig javaConfig;
    @Element
    protected AvailabilityService availabilityService;
    @Element(required=true)
    protected ThreadPools threadPools;
    @Element
    protected AlertService alertService;
    @Element
    protected GroupManagementService groupManagementService;
    @Element
    protected ManagementRules managementRules;
    @Element
    protected List<SystemProperty> systemProperty = new ConstrainedList<SystemProperty>("systemProperty", support);
    protected List<Property> property = new ConstrainedList<Property>("property", support);



    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
        try {
            support.fireVetoableChange("name", this.name, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.name = value;
    }

    /**
     * Gets the value of the dynamicReconfigurationEnabled property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getDynamicReconfigurationEnabled() {
        if (dynamicReconfigurationEnabled == null) {
            return "true";
        } else {
            return dynamicReconfigurationEnabled;
        }
    }

    /**
     * Sets the value of the dynamicReconfigurationEnabled property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDynamicReconfigurationEnabled(String value) {
        try {
            support.fireVetoableChange("dynamicReconfigurationEnabled", this.dynamicReconfigurationEnabled, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.dynamicReconfigurationEnabled = value;
    }

    /**
     * Gets the value of the httpService property.
     *
     * @return possible object is
     *         {@link HttpService }
     */
    public HttpService getHttpService() {
        return httpService;
    }

    /**
     * Sets the value of the httpService property.
     *
     * @param value allowed object is
     *              {@link HttpService }
     */
    public void setHttpService(HttpService value) {
        try {
            support.fireVetoableChange("httpService", this.httpService, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.httpService = value;
    }

    /**
     * Gets the value of the iiopService property.
     *
     * @return possible object is
     *         {@link IiopService }
     */
    public IiopService getIiopService() {
        return iiopService;
    }

    /**
     * Sets the value of the iiopService property.
     *
     * @param value allowed object is
     *              {@link IiopService }
     */
    public void setIiopService(IiopService value) {
        try {
            support.fireVetoableChange("iiopService", this.iiopService, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.iiopService = value;
    }

    /**
     * Gets the value of the adminService property.
     *
     * @return possible object is
     *         {@link AdminService }
     */
    public AdminService getAdminService() {
        return adminService;
    }

    /**
     * Sets the value of the adminService property.
     *
     * @param value allowed object is
     *              {@link AdminService }
     */
    public void setAdminService(AdminService value) {
        try {
            support.fireVetoableChange("adminService", this.adminService, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.adminService = value;
    }

    /**
     * Gets the value of the connectorService property.
     *
     * @return possible object is
     *         {@link ConnectorService }
     */
    public ConnectorService getConnectorService() {
        return connectorService;
    }

    /**
     * Sets the value of the connectorService property.
     *
     * @param value allowed object is
     *              {@link ConnectorService }
     */
    public void setConnectorService(ConnectorService value) {
        try {
            support.fireVetoableChange("connectorService", this.connectorService, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.connectorService = value;
    }

    /**
     * Gets the value of the webContainer property.
     *
     * @return possible object is
     *         {@link WebContainer }
     */
    public WebContainer getWebContainer() {
        return webContainer;
    }

    /**
     * Sets the value of the webContainer property.
     *
     * @param value allowed object is
     *              {@link WebContainer }
     */
    public void setWebContainer(WebContainer value) {
        try {
            support.fireVetoableChange("webContainer", this.webContainer, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.webContainer = value;
    }

    /**
     * Gets the value of the ejbContainer property.
     *
     * @return possible object is
     *         {@link EjbContainer }
     */
    public EjbContainer getEjbContainer() {
        return ejbContainer;
    }

    /**
     * Sets the value of the ejbContainer property.
     *
     * @param value allowed object is
     *              {@link EjbContainer }
     */
    public void setEjbContainer(EjbContainer value) {
        try {
            support.fireVetoableChange("ejbContainer", this.ejbContainer, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.ejbContainer = value;
    }

    /**
     * Gets the value of the mdbContainer property.
     *
     * @return possible object is
     *         {@link MdbContainer }
     */
    public MdbContainer getMdbContainer() {
        return mdbContainer;
    }

    /**
     * Sets the value of the mdbContainer property.
     *
     * @param value allowed object is
     *              {@link MdbContainer }
     */
    public void setMdbContainer(MdbContainer value) {
        try {
            support.fireVetoableChange("mdbContainer", this.mdbContainer, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.mdbContainer = value;
    }

    /**
     * Gets the value of the jmsService property.
     *
     * @return possible object is
     *         {@link JmsService }
     */
    public JmsService getJmsService() {
        return jmsService;
    }

    /**
     * Sets the value of the jmsService property.
     *
     * @param value allowed object is
     *              {@link JmsService }
     */
    public void setJmsService(JmsService value) {
        try {
            support.fireVetoableChange("jmsService", this.jmsService, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.jmsService = value;
    }

    /**
     * Gets the value of the logService property.
     *
     * @return possible object is
     *         {@link LogService }
     */
    public LogService getLogService() {
        return logService;
    }

    /**
     * Sets the value of the logService property.
     *
     * @param value allowed object is
     *              {@link LogService }
     */
    public void setLogService(LogService value) {
        try {
            support.fireVetoableChange("logService", this.logService, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.logService = value;
    }

    /**
     * Gets the value of the securityService property.
     *
     * @return possible object is
     *         {@link SecurityService }
     */
    public SecurityService getSecurityService() {
        return securityService;
    }

    /**
     * Sets the value of the securityService property.
     *
     * @param value allowed object is
     *              {@link SecurityService }
     */
    public void setSecurityService(SecurityService value) {
        try {
            support.fireVetoableChange("securityService", this.securityService, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.securityService = value;
    }

    /**
     * Gets the value of the transactionService property.
     *
     * @return possible object is
     *         {@link TransactionService }
     */
    public TransactionService getTransactionService() {
        return transactionService;
    }

    /**
     * Sets the value of the transactionService property.
     *
     * @param value allowed object is
     *              {@link TransactionService }
     */
    public void setTransactionService(TransactionService value) {
        try {
            support.fireVetoableChange("transactionService", this.transactionService, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.transactionService = value;
    }

    /**
     * Gets the value of the monitoringService property.
     *
     * @return possible object is
     *         {@link MonitoringService }
     */
    public MonitoringService getMonitoringService() {
        return monitoringService;
    }

    /**
     * Sets the value of the monitoringService property.
     *
     * @param value allowed object is
     *              {@link MonitoringService }
     */
    public void setMonitoringService(MonitoringService value) {
        try {
            support.fireVetoableChange("monitoringService", this.monitoringService, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.monitoringService = value;
    }

    /**
     * Gets the value of the diagnosticService property.
     *
     * @return possible object is
     *         {@link DiagnosticService }
     */
    public DiagnosticService getDiagnosticService() {
        return diagnosticService;
    }

    /**
     * Sets the value of the diagnosticService property.
     *
     * @param value allowed object is
     *              {@link DiagnosticService }
     */
    public void setDiagnosticService(DiagnosticService value) {
        try {
            support.fireVetoableChange("diagnosticService", this.diagnosticService, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.diagnosticService = value;
    }

    /**
     * Gets the value of the javaConfig property.
     *
     * @return possible object is
     *         {@link JavaConfig }
     */
    public JavaConfig getJavaConfig() {
        return javaConfig;
    }

    /**
     * Sets the value of the javaConfig property.
     *
     * @param value allowed object is
     *              {@link JavaConfig }
     */
    public void setJavaConfig(JavaConfig value) {
        try {
            support.fireVetoableChange("javaConfig", this.javaConfig, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.javaConfig = value;
    }

    /**
     * Gets the value of the availabilityService property.
     *
     * @return possible object is
     *         {@link AvailabilityService }
     */
    public AvailabilityService getAvailabilityService() {
        return availabilityService;
    }

    /**
     * Sets the value of the availabilityService property.
     *
     * @param value allowed object is
     *              {@link AvailabilityService }
     */
    public void setAvailabilityService(AvailabilityService value) {
        try {
            support.fireVetoableChange("availabilityService", this.availabilityService, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.availabilityService = value;
    }

    /**
     * Gets the value of the threadPools property.
     *
     * @return possible object is
     *         {@link ThreadPools }
     */
    public ThreadPools getThreadPools() {
        return threadPools;
    }

    /**
     * Sets the value of the threadPools property.
     *
     * @param value allowed object is
     *              {@link ThreadPools }
     */
    public void setThreadPools(ThreadPools value) {
        try {
            support.fireVetoableChange("threadPools", this.threadPools, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.threadPools = value;
    }

    /**
     * Gets the value of the alertService property.
     *
     * @return possible object is
     *         {@link AlertService }
     */
    public AlertService getAlertService() {
        return alertService;
    }

    /**
     * Sets the value of the alertService property.
     *
     * @param value allowed object is
     *              {@link AlertService }
     */
    public void setAlertService(AlertService value) {
        try {
            support.fireVetoableChange("alertService", this.alertService, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.alertService = value;
    }

    /**
     * Gets the value of the groupManagementService property.
     *
     * @return possible object is
     *         {@link GroupManagementService }
     */
    public GroupManagementService getGroupManagementService() {
        return groupManagementService;
    }

    /**
     * Sets the value of the groupManagementService property.
     *
     * @param value allowed object is
     *              {@link GroupManagementService }
     */
    public void setGroupManagementService(GroupManagementService value) {
        try {
            support.fireVetoableChange("groupManagementService", this.groupManagementService, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.groupManagementService = value;
    }

    /**
     * Gets the value of the managementRules property.
     *
     * @return possible object is
     *         {@link ManagementRules }
     */
    public ManagementRules getManagementRules() {
        return managementRules;
    }

    /**
     * Sets the value of the managementRules property.
     *
     * @param value allowed object is
     *              {@link ManagementRules }
     */
    public void setManagementRules(ManagementRules value) {
        try {
            support.fireVetoableChange("managementRules", this.managementRules, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.managementRules = value;
    }

    /**
     * Gets the value of the systemProperty property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the systemProperty property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSystemProperty().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link SystemProperty }
     */
    public List<SystemProperty> getSystemProperty() {
        return this.systemProperty;
    }

    /**
     * Gets the value of the property property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the property property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProperty().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link Property }
     */
    public List<Property> getProperty() {

        return this.property;
    }

    public void addVetoableChangeListener(VetoableChangeListener param0) {
        support.addVetoableChangeListener(param0);
    }

    public void addVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.addVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.removeVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(VetoableChangeListener param0) {
        support.removeVetoableChangeListener(param0);
    }

}
