//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-04/12/2007 12:08 AM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.24 at 01:25:15 PM PDT 
//


package com.sun.enterprise.config.serverbeans;

import org.jvnet.hk2.config.Attribute;
import org.jvnet.hk2.config.Configured;

import java.beans.PropertyVetoException;
import java.beans.VetoableChangeListener;
import java.beans.VetoableChangeSupport;
import java.io.Serializable;


/**
 *
 */

/* @XmlType(name = "") */
@Configured
public class ConnectionPool
        implements Serializable {

	final transient private VetoableChangeSupport support = new VetoableChangeSupport(this);

    private final static long serialVersionUID = 1L;
    @Attribute

    protected String queueSizeInBytes;
    @Attribute

    protected String maxPendingCount;
    @Attribute

    protected String receiveBufferSizeInBytes;
    @Attribute

    protected String sendBufferSizeInBytes;



    /**
     * Gets the value of the queueSizeInBytes property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getQueueSizeInBytes() {
        if (queueSizeInBytes == null) {
            return "4096";
        } else {
            return queueSizeInBytes;
        }
    }

    /**
     * Sets the value of the queueSizeInBytes property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setQueueSizeInBytes(String value) {
        try {
            support.fireVetoableChange("queueSizeInBytes", this.queueSizeInBytes, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.queueSizeInBytes = value;
    }

    /**
     * Gets the value of the maxPendingCount property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getMaxPendingCount() {
        if (maxPendingCount == null) {
            return "4096";
        } else {
            return maxPendingCount;
        }
    }

    /**
     * Sets the value of the maxPendingCount property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMaxPendingCount(String value) {
        try {
            support.fireVetoableChange("maxPendingCount", this.maxPendingCount, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.maxPendingCount = value;
    }

    /**
     * Gets the value of the receiveBufferSizeInBytes property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getReceiveBufferSizeInBytes() {
        if (receiveBufferSizeInBytes == null) {
            return "4096";
        } else {
            return receiveBufferSizeInBytes;
        }
    }

    /**
     * Sets the value of the receiveBufferSizeInBytes property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setReceiveBufferSizeInBytes(String value) {
        try {
            support.fireVetoableChange("receiveBufferSizeInBytes", this.receiveBufferSizeInBytes, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.receiveBufferSizeInBytes = value;
    }

    /**
     * Gets the value of the sendBufferSizeInBytes property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getSendBufferSizeInBytes() {
        if (sendBufferSizeInBytes == null) {
            return "8192";
        } else {
            return sendBufferSizeInBytes;
        }
    }

    /**
     * Sets the value of the sendBufferSizeInBytes property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSendBufferSizeInBytes(String value) {
        try {
            support.fireVetoableChange("sendBufferSizeInBytes", this.sendBufferSizeInBytes, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.sendBufferSizeInBytes = value;
    }

    public void addVetoableChangeListener(VetoableChangeListener param0) {
        support.addVetoableChangeListener(param0);
    }

    public void addVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.addVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.removeVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(VetoableChangeListener param0) {
        support.removeVetoableChangeListener(param0);
    }

}
