//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-04/12/2007 12:08 AM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.24 at 01:25:15 PM PDT 
//


package com.sun.enterprise.config.serverbeans;

import org.jvnet.hk2.config.Attribute;
import org.jvnet.hk2.config.Configured;

import java.beans.PropertyVetoException;
import java.beans.VetoableChangeListener;
import java.beans.VetoableChangeSupport;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 *
 */

/* @XmlType(name = "", propOrder = {
    "property"
}) */
@Configured
public class DasConfig
        implements Serializable {

	final transient private VetoableChangeSupport support = new VetoableChangeSupport(this);

    private final static long serialVersionUID = 1L;
    @Attribute

    protected String dynamicReloadEnabled;
    @Attribute

    protected String dynamicReloadPollIntervalInSeconds;
    @Attribute

    protected String autodeployEnabled;
    @Attribute

    protected String autodeployPollingIntervalInSeconds;
    @Attribute

    protected String autodeployDir;
    @Attribute

    protected String autodeployVerifierEnabled;
    @Attribute

    protected String autodeployJspPrecompilationEnabled;
    @Attribute

    protected String deployXmlValidation;
    @Attribute

    protected String adminSessionTimeoutInMinutes;
    protected List<Property> property = new ConstrainedList<Property>("property", support);



    /**
     * Gets the value of the dynamicReloadEnabled property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getDynamicReloadEnabled() {
        if (dynamicReloadEnabled == null) {
            return "false";
        } else {
            return dynamicReloadEnabled;
        }
    }

    /**
     * Sets the value of the dynamicReloadEnabled property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDynamicReloadEnabled(String value) {
        try {
            support.fireVetoableChange("dynamicReloadEnabled", this.dynamicReloadEnabled, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.dynamicReloadEnabled = value;
    }

    /**
     * Gets the value of the dynamicReloadPollIntervalInSeconds property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getDynamicReloadPollIntervalInSeconds() {
        if (dynamicReloadPollIntervalInSeconds == null) {
            return "2";
        } else {
            return dynamicReloadPollIntervalInSeconds;
        }
    }

    /**
     * Sets the value of the dynamicReloadPollIntervalInSeconds property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDynamicReloadPollIntervalInSeconds(String value) {
        try {
            support.fireVetoableChange("dynamicReloadPollIntervalInSeconds", this.dynamicReloadPollIntervalInSeconds, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.dynamicReloadPollIntervalInSeconds = value;
    }

    /**
     * Gets the value of the autodeployEnabled property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getAutodeployEnabled() {
        if (autodeployEnabled == null) {
            return "false";
        } else {
            return autodeployEnabled;
        }
    }

    /**
     * Sets the value of the autodeployEnabled property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAutodeployEnabled(String value) {
        try {
            support.fireVetoableChange("autodeployEnabled", this.autodeployEnabled, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.autodeployEnabled = value;
    }

    /**
     * Gets the value of the autodeployPollingIntervalInSeconds property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getAutodeployPollingIntervalInSeconds() {
        if (autodeployPollingIntervalInSeconds == null) {
            return "2";
        } else {
            return autodeployPollingIntervalInSeconds;
        }
    }

    /**
     * Sets the value of the autodeployPollingIntervalInSeconds property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAutodeployPollingIntervalInSeconds(String value) {
        try {
            support.fireVetoableChange("autodeployPollingIntervalInSeconds", this.autodeployPollingIntervalInSeconds, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.autodeployPollingIntervalInSeconds = value;
    }

    /**
     * Gets the value of the autodeployDir property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getAutodeployDir() {
        if (autodeployDir == null) {
            return "autodeploy";
        } else {
            return autodeployDir;
        }
    }

    /**
     * Sets the value of the autodeployDir property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAutodeployDir(String value) {
        try {
            support.fireVetoableChange("autodeployDir", this.autodeployDir, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.autodeployDir = value;
    }

    /**
     * Gets the value of the autodeployVerifierEnabled property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getAutodeployVerifierEnabled() {
        if (autodeployVerifierEnabled == null) {
            return "false";
        } else {
            return autodeployVerifierEnabled;
        }
    }

    /**
     * Sets the value of the autodeployVerifierEnabled property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAutodeployVerifierEnabled(String value) {
        try {
            support.fireVetoableChange("autodeployVerifierEnabled", this.autodeployVerifierEnabled, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.autodeployVerifierEnabled = value;
    }

    /**
     * Gets the value of the autodeployJspPrecompilationEnabled property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getAutodeployJspPrecompilationEnabled() {
        if (autodeployJspPrecompilationEnabled == null) {
            return "false";
        } else {
            return autodeployJspPrecompilationEnabled;
        }
    }

    /**
     * Sets the value of the autodeployJspPrecompilationEnabled property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAutodeployJspPrecompilationEnabled(String value) {
        try {
            support.fireVetoableChange("autodeployJspPrecompilationEnabled", this.autodeployJspPrecompilationEnabled, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.autodeployJspPrecompilationEnabled = value;
    }

    /**
     * Gets the value of the deployXmlValidation property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getDeployXmlValidation() {
        if (deployXmlValidation == null) {
            return "full";
        } else {
            return deployXmlValidation;
        }
    }

    /**
     * Sets the value of the deployXmlValidation property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDeployXmlValidation(String value) {
        try {
            support.fireVetoableChange("deployXmlValidation", this.deployXmlValidation, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.deployXmlValidation = value;
    }

    /**
     * Gets the value of the adminSessionTimeoutInMinutes property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getAdminSessionTimeoutInMinutes() {
        if (adminSessionTimeoutInMinutes == null) {
            return "60";
        } else {
            return adminSessionTimeoutInMinutes;
        }
    }

    /**
     * Sets the value of the adminSessionTimeoutInMinutes property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAdminSessionTimeoutInMinutes(String value) {
        try {
            support.fireVetoableChange("adminSessionTimeoutInMinutes", this.adminSessionTimeoutInMinutes, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.adminSessionTimeoutInMinutes = value;
    }

    /**
     * Gets the value of the property property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the property property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProperty().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link Property }
     */
    public List<Property> getProperty() {
        return this.property;
    }

    public void addVetoableChangeListener(VetoableChangeListener param0) {
        support.addVetoableChangeListener(param0);
    }

    public void addVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.addVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.removeVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(VetoableChangeListener param0) {
        support.removeVetoableChangeListener(param0);
    }

}
