//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-04/12/2007 12:08 AM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.24 at 01:25:15 PM PDT 
//


package com.sun.enterprise.config.serverbeans;

import org.jvnet.hk2.config.Attribute;
import org.jvnet.hk2.config.Configured;
import org.jvnet.hk2.config.Element;

import java.beans.PropertyVetoException;
import java.beans.VetoableChangeListener;
import java.beans.VetoableChangeSupport;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 *
 */

/* @XmlType(name = "", propOrder = {
    "applications",
    "resources",
    "configs",
    "servers",
    "clusters",
    "nodeAgents",
    "lbConfigs",
    "loadBalancers",
    "systemProperty",
    "property"
}) */
@Configured
public class Domain
        implements Serializable {

	final transient private VetoableChangeSupport support = new VetoableChangeSupport(this);

    private final static long serialVersionUID = 1L;
    @Attribute

    protected String applicationRoot;
    @Attribute

    protected String logRoot;
    @Attribute

    protected String locale;
    protected Applications applications;
    protected Resources resources;
    @Element(required=true)
    protected Configs configs;
    @Element(required=true)
    protected Servers servers;
    protected Clusters clusters;
    @Element
    protected NodeAgents nodeAgents;
    @Element
    protected LbConfigs lbConfigs;
    @Element
    protected LoadBalancers loadBalancers;
    @Element
    protected List<SystemProperty> systemProperty = new ConstrainedList<SystemProperty>("systemProperty", support);
    protected List<Property> property = new ConstrainedList<Property>("property", support);



    /**
     * Gets the value of the applicationRoot property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getApplicationRoot() {
        return applicationRoot;
    }

    /**
     * Sets the value of the applicationRoot property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setApplicationRoot(String value) {
        try {
            support.fireVetoableChange("applicationRoot", this.applicationRoot, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.applicationRoot = value;
    }

    /**
     * Gets the value of the logRoot property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getLogRoot() {
        return logRoot;
    }

    /**
     * Sets the value of the logRoot property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLogRoot(String value) {
        try {
            support.fireVetoableChange("logRoot", this.logRoot, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.logRoot = value;
    }

    /**
     * Gets the value of the locale property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getLocale() {
        return locale;
    }

    /**
     * Sets the value of the locale property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLocale(String value) {
        try {
            support.fireVetoableChange("locale", this.locale, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.locale = value;
    }

    /**
     * Gets the value of the applications property.
     *
     * @return possible object is
     *         {@link Applications }
     */
    public Applications getApplications() {
        return applications;
    }

    /**
     * Sets the value of the applications property.
     *
     * @param value allowed object is
     *              {@link Applications }
     */
    public void setApplications(Applications value) {
        try {
            support.fireVetoableChange("applications", this.applications, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.applications = value;
    }

    /**
     * Gets the value of the resources property.
     *
     * @return possible object is
     *         {@link Resources }
     */
    public Resources getResources() {
        return resources;
    }

    /**
     * Sets the value of the resources property.
     *
     * @param value allowed object is
     *              {@link Resources }
     */
    public void setResources(Resources value) {
        try {
            support.fireVetoableChange("resources", this.resources, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.resources = value;
    }

    /**
     * Gets the value of the configs property.
     *
     * @return possible object is
     *         {@link Configs }
     */
    public Configs getConfigs() {
        return configs;
    }

    /**
     * Sets the value of the configs property.
     *
     * @param value allowed object is
     *              {@link Configs }
     */
    public void setConfigs(Configs value) {
        try {
            support.fireVetoableChange("configs", this.configs, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.configs = value;
    }

    /**
     * Gets the value of the servers property.
     *
     * @return possible object is
     *         {@link Servers }
     */
    public Servers getServers() {
        return servers;
    }

    /**
     * Sets the value of the servers property.
     *
     * @param value allowed object is
     *              {@link Servers }
     */
    public void setServers(Servers value) {
        try {
            support.fireVetoableChange("servers", this.servers, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.servers = value;
    }

    /**
     * Gets the value of the clusters property.
     *
     * @return possible object is
     *         {@link Clusters }
     */
    public Clusters getClusters() {
        return clusters;
    }

    /**
     * Sets the value of the clusters property.
     *
     * @param value allowed object is
     *              {@link Clusters }
     */
    public void setClusters(Clusters value) {
        try {
            support.fireVetoableChange("clusters", this.clusters, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.clusters = value;
    }

    /**
     * Gets the value of the nodeAgents property.
     *
     * @return possible object is
     *         {@link NodeAgents }
     */
    public NodeAgents getNodeAgents() {
        return nodeAgents;
    }

    /**
     * Sets the value of the nodeAgents property.
     *
     * @param value allowed object is
     *              {@link NodeAgents }
     */
    public void setNodeAgents(NodeAgents value) {
        try {
            support.fireVetoableChange("nodeAgents", this.nodeAgents, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.nodeAgents = value;
    }

    /**
     * Gets the value of the lbConfigs property.
     *
     * @return possible object is
     *         {@link LbConfigs }
     */
    public LbConfigs getLbConfigs() {
        return lbConfigs;
    }

    /**
     * Sets the value of the lbConfigs property.
     *
     * @param value allowed object is
     *              {@link LbConfigs }
     */
    public void setLbConfigs(LbConfigs value) {
        try {
            support.fireVetoableChange("lbConfigs", this.lbConfigs, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.lbConfigs = value;
    }

    /**
     * Gets the value of the loadBalancers property.
     *
     * @return possible object is
     *         {@link LoadBalancers }
     */
    public LoadBalancers getLoadBalancers() {
        return loadBalancers;
    }

    /**
     * Sets the value of the loadBalancers property.
     *
     * @param value allowed object is
     *              {@link LoadBalancers }
     */
    public void setLoadBalancers(LoadBalancers value) {
        try {
            support.fireVetoableChange("loadBalancers", this.loadBalancers, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.loadBalancers = value;
    }

    /**
     * Gets the value of the systemProperty property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the systemProperty property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSystemProperty().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link SystemProperty }
     */
    public List<SystemProperty> getSystemProperty() {
        return this.systemProperty;
    }

    /**
     * Gets the value of the property property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the property property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProperty().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link Property }
     */
    public List<Property> getProperty() {
        return this.property;
    }

    public void addVetoableChangeListener(VetoableChangeListener param0) {
        support.addVetoableChangeListener(param0);
    }

    public void addVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.addVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.removeVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(VetoableChangeListener param0) {
        support.removeVetoableChangeListener(param0);
    }

}
