//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-04/12/2007 12:08 AM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.24 at 01:25:15 PM PDT 
//


package com.sun.enterprise.config.serverbeans;

import org.jvnet.hk2.config.Attribute;
import org.jvnet.hk2.config.Configured;

import java.beans.PropertyVetoException;
import java.beans.VetoableChangeListener;
import java.beans.VetoableChangeSupport;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 *
 */

/* @XmlType(name = "", propOrder = {
    "property"
}) */
@Configured
public class EjbContainerAvailability
        implements Serializable {

	final transient private VetoableChangeSupport support = new VetoableChangeSupport(this);

    private final static long serialVersionUID = 1L;
    @Attribute

    protected String availabilityEnabled;
    @Attribute

    protected String sfsbHaPersistenceType;
    @Attribute

    protected String sfsbPersistenceType;
    @Attribute

    protected String sfsbCheckpointEnabled;
    @Attribute

    protected String sfsbQuickCheckpointEnabled;
    @Attribute

    protected String sfsbStorePoolName;
    protected List<Property> property = new ConstrainedList<Property>("property", support);



    /**
     * Gets the value of the availabilityEnabled property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getAvailabilityEnabled() {
        return availabilityEnabled;
    }

    /**
     * Sets the value of the availabilityEnabled property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAvailabilityEnabled(String value) {
        try {
            support.fireVetoableChange("availabilityEnabled", this.availabilityEnabled, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.availabilityEnabled = value;
    }

    /**
     * Gets the value of the sfsbHaPersistenceType property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getSfsbHaPersistenceType() {
        if (sfsbHaPersistenceType == null) {
            return "ha";
        } else {
            return sfsbHaPersistenceType;
        }
    }

    /**
     * Sets the value of the sfsbHaPersistenceType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSfsbHaPersistenceType(String value) {
        try {
            support.fireVetoableChange("sfsbHaPersistenceType", this.sfsbHaPersistenceType, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.sfsbHaPersistenceType = value;
    }

    /**
     * Gets the value of the sfsbPersistenceType property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getSfsbPersistenceType() {
        if (sfsbPersistenceType == null) {
            return "file";
        } else {
            return sfsbPersistenceType;
        }
    }

    /**
     * Sets the value of the sfsbPersistenceType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSfsbPersistenceType(String value) {
        try {
            support.fireVetoableChange("sfsbPersistenceType", this.sfsbPersistenceType, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.sfsbPersistenceType = value;
    }

    /**
     * Gets the value of the sfsbCheckpointEnabled property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getSfsbCheckpointEnabled() {
        return sfsbCheckpointEnabled;
    }

    /**
     * Sets the value of the sfsbCheckpointEnabled property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSfsbCheckpointEnabled(String value) {
        try {
            support.fireVetoableChange("sfsbCheckpointEnabled", this.sfsbCheckpointEnabled, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.sfsbCheckpointEnabled = value;
    }

    /**
     * Gets the value of the sfsbQuickCheckpointEnabled property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getSfsbQuickCheckpointEnabled() {
        return sfsbQuickCheckpointEnabled;
    }

    /**
     * Sets the value of the sfsbQuickCheckpointEnabled property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSfsbQuickCheckpointEnabled(String value) {
        try {
            support.fireVetoableChange("sfsbQuickCheckpointEnabled", this.sfsbQuickCheckpointEnabled, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.sfsbQuickCheckpointEnabled = value;
    }

    /**
     * Gets the value of the sfsbStorePoolName property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getSfsbStorePoolName() {
        return sfsbStorePoolName;
    }

    /**
     * Sets the value of the sfsbStorePoolName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSfsbStorePoolName(String value) {
        try {
            support.fireVetoableChange("sfsbStorePoolName", this.sfsbStorePoolName, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.sfsbStorePoolName = value;
    }

    /**
     * Gets the value of the property property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the property property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProperty().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link Property }
     */
    public List<Property> getProperty() {
        return this.property;
    }

    public void addVetoableChangeListener(VetoableChangeListener param0) {
        support.addVetoableChangeListener(param0);
    }

    public void addVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.addVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.removeVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(VetoableChangeListener param0) {
        support.removeVetoableChangeListener(param0);
    }

}
