//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-04/12/2007 12:08 AM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.24 at 01:25:15 PM PDT 
//


package com.sun.enterprise.config.serverbeans;

import org.jvnet.hk2.config.Attribute;
import org.jvnet.hk2.config.Configured;
import org.jvnet.hk2.config.Element;

import java.beans.PropertyVetoException;
import java.beans.VetoableChangeListener;
import java.beans.VetoableChangeSupport;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 *
 */

/* @XmlType(name = "", propOrder = {
    "ejbTimerService",
    "property"
}) */
@Configured
public class EjbContainer
        implements Serializable {

	final transient private VetoableChangeSupport support = new VetoableChangeSupport(this);

    private final static long serialVersionUID = 1L;
    @Attribute

    protected String steadyPoolSize;
    @Attribute

    protected String poolResizeQuantity;
    @Attribute

    protected String maxPoolSize;
    @Attribute

    protected String cacheResizeQuantity;
    @Attribute

    protected String maxCacheSize;
    @Attribute

    protected String poolIdleTimeoutInSeconds;
    @Attribute

    protected String cacheIdleTimeoutInSeconds;
    @Attribute

    protected String removalTimeoutInSeconds;
    @Attribute

    protected String victimSelectionPolicy;
    @Attribute

    protected String commitOption;
    @Attribute

    protected String sessionStore;
    @Element
    protected EjbTimerService ejbTimerService;
    protected List<Property> property = new ConstrainedList<Property>("property", support);



    /**
     * Gets the value of the steadyPoolSize property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getSteadyPoolSize() {
        if (steadyPoolSize == null) {
            return "32";
        } else {
            return steadyPoolSize;
        }
    }

    /**
     * Sets the value of the steadyPoolSize property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSteadyPoolSize(String value) {
        try {
            support.fireVetoableChange("steadyPoolSize", this.steadyPoolSize, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.steadyPoolSize = value;
    }

    /**
     * Gets the value of the poolResizeQuantity property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getPoolResizeQuantity() {
        if (poolResizeQuantity == null) {
            return "16";
        } else {
            return poolResizeQuantity;
        }
    }

    /**
     * Sets the value of the poolResizeQuantity property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPoolResizeQuantity(String value) {
        try {
            support.fireVetoableChange("poolResizeQuantity", this.poolResizeQuantity, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.poolResizeQuantity = value;
    }

    /**
     * Gets the value of the maxPoolSize property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getMaxPoolSize() {
        if (maxPoolSize == null) {
            return "64";
        } else {
            return maxPoolSize;
        }
    }

    /**
     * Sets the value of the maxPoolSize property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMaxPoolSize(String value) {
        try {
            support.fireVetoableChange("maxPoolSize", this.maxPoolSize, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.maxPoolSize = value;
    }

    /**
     * Gets the value of the cacheResizeQuantity property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getCacheResizeQuantity() {
        if (cacheResizeQuantity == null) {
            return "32";
        } else {
            return cacheResizeQuantity;
        }
    }

    /**
     * Sets the value of the cacheResizeQuantity property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCacheResizeQuantity(String value) {
        try {
            support.fireVetoableChange("cacheResizeQuantity", this.cacheResizeQuantity, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.cacheResizeQuantity = value;
    }

    /**
     * Gets the value of the maxCacheSize property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getMaxCacheSize() {
        if (maxCacheSize == null) {
            return "512";
        } else {
            return maxCacheSize;
        }
    }

    /**
     * Sets the value of the maxCacheSize property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMaxCacheSize(String value) {
        try {
            support.fireVetoableChange("maxCacheSize", this.maxCacheSize, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.maxCacheSize = value;
    }

    /**
     * Gets the value of the poolIdleTimeoutInSeconds property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getPoolIdleTimeoutInSeconds() {
        if (poolIdleTimeoutInSeconds == null) {
            return "600";
        } else {
            return poolIdleTimeoutInSeconds;
        }
    }

    /**
     * Sets the value of the poolIdleTimeoutInSeconds property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPoolIdleTimeoutInSeconds(String value) {
        try {
            support.fireVetoableChange("poolIdleTimeoutInSeconds", this.poolIdleTimeoutInSeconds, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.poolIdleTimeoutInSeconds = value;
    }

    /**
     * Gets the value of the cacheIdleTimeoutInSeconds property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getCacheIdleTimeoutInSeconds() {
        if (cacheIdleTimeoutInSeconds == null) {
            return "600";
        } else {
            return cacheIdleTimeoutInSeconds;
        }
    }

    /**
     * Sets the value of the cacheIdleTimeoutInSeconds property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCacheIdleTimeoutInSeconds(String value) {
        try {
            support.fireVetoableChange("cacheIdleTimeoutInSeconds", this.cacheIdleTimeoutInSeconds, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.cacheIdleTimeoutInSeconds = value;
    }

    /**
     * Gets the value of the removalTimeoutInSeconds property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getRemovalTimeoutInSeconds() {
        if (removalTimeoutInSeconds == null) {
            return "5400";
        } else {
            return removalTimeoutInSeconds;
        }
    }

    /**
     * Sets the value of the removalTimeoutInSeconds property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRemovalTimeoutInSeconds(String value) {
        try {
            support.fireVetoableChange("removalTimeoutInSeconds", this.removalTimeoutInSeconds, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.removalTimeoutInSeconds = value;
    }

    /**
     * Gets the value of the victimSelectionPolicy property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getVictimSelectionPolicy() {
        if (victimSelectionPolicy == null) {
            return "nru";
        } else {
            return victimSelectionPolicy;
        }
    }

    /**
     * Sets the value of the victimSelectionPolicy property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setVictimSelectionPolicy(String value) {
        try {
            support.fireVetoableChange("victimSelectionPolicy", this.victimSelectionPolicy, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.victimSelectionPolicy = value;
    }

    /**
     * Gets the value of the commitOption property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getCommitOption() {
        if (commitOption == null) {
            return "B";
        } else {
            return commitOption;
        }
    }

    /**
     * Sets the value of the commitOption property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCommitOption(String value) {
        try {
            support.fireVetoableChange("commitOption", this.commitOption, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.commitOption = value;
    }

    /**
     * Gets the value of the sessionStore property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getSessionStore() {
        return sessionStore;
    }

    /**
     * Sets the value of the sessionStore property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSessionStore(String value) {
        try {
            support.fireVetoableChange("sessionStore", this.sessionStore, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.sessionStore = value;
    }

    /**
     * Gets the value of the ejbTimerService property.
     *
     * @return possible object is
     *         {@link EjbTimerService }
     */
    public EjbTimerService getEjbTimerService() {
        return ejbTimerService;
    }

    /**
     * Sets the value of the ejbTimerService property.
     *
     * @param value allowed object is
     *              {@link EjbTimerService }
     */
    public void setEjbTimerService(EjbTimerService value) {
        try {
            support.fireVetoableChange("ejbTimerService", this.ejbTimerService, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.ejbTimerService = value;
    }

    /**
     * Gets the value of the property property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the property property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProperty().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link Property }
     */
    public List<Property> getProperty() {
        return this.property;
    }

    public void addVetoableChangeListener(VetoableChangeListener param0) {
        support.addVetoableChangeListener(param0);
    }

    public void addVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.addVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.removeVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(VetoableChangeListener param0) {
        support.removeVetoableChangeListener(param0);
    }

}
