//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-04/12/2007 12:08 AM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.24 at 01:25:15 PM PDT 
//


package com.sun.enterprise.config.serverbeans;

import org.jvnet.hk2.config.Attribute;
import org.jvnet.hk2.config.Configured;

import java.beans.PropertyVetoException;
import java.beans.VetoableChangeListener;
import java.beans.VetoableChangeSupport;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 *
 */

/* @XmlType(name = "", propOrder = {
    "property"
}) */
@Configured
public class GroupManagementService
        implements Serializable {

	final transient private VetoableChangeSupport support = new VetoableChangeSupport(this);

    private final static long serialVersionUID = 1L;
    @Attribute

    protected String fdProtocolMaxTries;
    @Attribute

    protected String fdProtocolTimeoutInMillis;
    @Attribute

    protected String mergeProtocolMaxIntervalInMillis;
    @Attribute

    protected String mergeProtocolMinIntervalInMillis;
    @Attribute

    protected String pingProtocolTimeoutInMillis;
    @Attribute

    protected String vsProtocolTimeoutInMillis;
    protected List<Property> property = new ConstrainedList<Property>("property", support);



    /**
     * Gets the value of the fdProtocolMaxTries property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getFdProtocolMaxTries() {
        if (fdProtocolMaxTries == null) {
            return "3";
        } else {
            return fdProtocolMaxTries;
        }
    }

    /**
     * Sets the value of the fdProtocolMaxTries property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFdProtocolMaxTries(String value) {
        try {
            support.fireVetoableChange("fdProtocolMaxTries", this.fdProtocolMaxTries, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.fdProtocolMaxTries = value;
    }

    /**
     * Gets the value of the fdProtocolTimeoutInMillis property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getFdProtocolTimeoutInMillis() {
        if (fdProtocolTimeoutInMillis == null) {
            return "2000";
        } else {
            return fdProtocolTimeoutInMillis;
        }
    }

    /**
     * Sets the value of the fdProtocolTimeoutInMillis property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFdProtocolTimeoutInMillis(String value) {
        try {
            support.fireVetoableChange("fdProtocolTimeoutInMillis", this.fdProtocolTimeoutInMillis, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.fdProtocolTimeoutInMillis = value;
    }

    /**
     * Gets the value of the mergeProtocolMaxIntervalInMillis property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getMergeProtocolMaxIntervalInMillis() {
        if (mergeProtocolMaxIntervalInMillis == null) {
            return "10000";
        } else {
            return mergeProtocolMaxIntervalInMillis;
        }
    }

    /**
     * Sets the value of the mergeProtocolMaxIntervalInMillis property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMergeProtocolMaxIntervalInMillis(String value) {
        try {
            support.fireVetoableChange("mergeProtocolMaxIntervalInMillis", this.mergeProtocolMaxIntervalInMillis, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.mergeProtocolMaxIntervalInMillis = value;
    }

    /**
     * Gets the value of the mergeProtocolMinIntervalInMillis property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getMergeProtocolMinIntervalInMillis() {
        if (mergeProtocolMinIntervalInMillis == null) {
            return "5000";
        } else {
            return mergeProtocolMinIntervalInMillis;
        }
    }

    /**
     * Sets the value of the mergeProtocolMinIntervalInMillis property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMergeProtocolMinIntervalInMillis(String value) {
        try {
            support.fireVetoableChange("mergeProtocolMinIntervalInMillis", this.mergeProtocolMinIntervalInMillis, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.mergeProtocolMinIntervalInMillis = value;
    }

    /**
     * Gets the value of the pingProtocolTimeoutInMillis property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getPingProtocolTimeoutInMillis() {
        if (pingProtocolTimeoutInMillis == null) {
            return "2000";
        } else {
            return pingProtocolTimeoutInMillis;
        }
    }

    /**
     * Sets the value of the pingProtocolTimeoutInMillis property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPingProtocolTimeoutInMillis(String value) {
        try {
            support.fireVetoableChange("pingProtocolTimeoutInMillis", this.pingProtocolTimeoutInMillis, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.pingProtocolTimeoutInMillis = value;
    }

    /**
     * Gets the value of the vsProtocolTimeoutInMillis property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getVsProtocolTimeoutInMillis() {
        if (vsProtocolTimeoutInMillis == null) {
            return "1500";
        } else {
            return vsProtocolTimeoutInMillis;
        }
    }

    /**
     * Sets the value of the vsProtocolTimeoutInMillis property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setVsProtocolTimeoutInMillis(String value) {
        try {
            support.fireVetoableChange("vsProtocolTimeoutInMillis", this.vsProtocolTimeoutInMillis, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.vsProtocolTimeoutInMillis = value;
    }

    /**
     * Gets the value of the property property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the property property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProperty().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link Property }
     */
    public List<Property> getProperty() {
        return this.property;
    }

    public void addVetoableChangeListener(VetoableChangeListener param0) {
        support.addVetoableChangeListener(param0);
    }

    public void addVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.addVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.removeVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(VetoableChangeListener param0) {
        support.removeVetoableChangeListener(param0);
    }

}
