//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-04/12/2007 12:08 AM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.24 at 01:25:15 PM PDT 
//


package com.sun.enterprise.config.serverbeans;

import org.jvnet.hk2.config.Attribute;
import org.jvnet.hk2.config.Configured;

import java.beans.PropertyVetoException;
import java.beans.VetoableChangeListener;
import java.beans.VetoableChangeSupport;
import java.io.Serializable;


/**
 *
 */

/* @XmlType(name = "") */
@Configured
public class HttpProtocol
        implements Serializable {

	final transient private VetoableChangeSupport support = new VetoableChangeSupport(this);

    private final static long serialVersionUID = 1L;
    @Attribute

    protected String version;
    @Attribute

    protected String dnsLookupEnabled;
    @Attribute

    protected String forcedType;
    @Attribute

    protected String defaultType;
    @Attribute

    protected String forcedResponseType;
    @Attribute

    protected String defaultResponseType;
    @Attribute

    protected String sslEnabled;



    /**
     * Gets the value of the version property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getVersion() {
        if (version == null) {
            return "HTTP/1.1";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setVersion(String value) {
        try {
            support.fireVetoableChange("version", this.version, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.version = value;
    }

    /**
     * Gets the value of the dnsLookupEnabled property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getDnsLookupEnabled() {
        if (dnsLookupEnabled == null) {
            return "false";
        } else {
            return dnsLookupEnabled;
        }
    }

    /**
     * Sets the value of the dnsLookupEnabled property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDnsLookupEnabled(String value) {
        try {
            support.fireVetoableChange("dnsLookupEnabled", this.dnsLookupEnabled, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.dnsLookupEnabled = value;
    }

    /**
     * Gets the value of the forcedType property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getForcedType() {
        if (forcedType == null) {
            return "text/html; charset=iso-8859-1";
        } else {
            return forcedType;
        }
    }

    /**
     * Sets the value of the forcedType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setForcedType(String value) {
        try {
            support.fireVetoableChange("forcedType", this.forcedType, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.forcedType = value;
    }

    /**
     * Gets the value of the defaultType property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getDefaultType() {
        if (defaultType == null) {
            return "text/html; charset=iso-8859-1";
        } else {
            return defaultType;
        }
    }

    /**
     * Sets the value of the defaultType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDefaultType(String value) {
        try {
            support.fireVetoableChange("defaultType", this.defaultType, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.defaultType = value;
    }

    /**
     * Gets the value of the forcedResponseType property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getForcedResponseType() {
        if (forcedResponseType == null) {
            return "AttributeDeprecated";
        } else {
            return forcedResponseType;
        }
    }

    /**
     * Sets the value of the forcedResponseType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setForcedResponseType(String value) {
        try {
            support.fireVetoableChange("forcedResponseType", this.forcedResponseType, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.forcedResponseType = value;
    }

    /**
     * Gets the value of the defaultResponseType property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getDefaultResponseType() {
        if (defaultResponseType == null) {
            return "AttributeDeprecated";
        } else {
            return defaultResponseType;
        }
    }

    /**
     * Sets the value of the defaultResponseType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDefaultResponseType(String value) {
        try {
            support.fireVetoableChange("defaultResponseType", this.defaultResponseType, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.defaultResponseType = value;
    }

    /**
     * Gets the value of the sslEnabled property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getSslEnabled() {
        if (sslEnabled == null) {
            return "true";
        } else {
            return sslEnabled;
        }
    }

    /**
     * Sets the value of the sslEnabled property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSslEnabled(String value) {
        try {
            support.fireVetoableChange("sslEnabled", this.sslEnabled, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.sslEnabled = value;
    }

    public void addVetoableChangeListener(VetoableChangeListener param0) {
        support.addVetoableChangeListener(param0);
    }

    public void addVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.addVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.removeVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(VetoableChangeListener param0) {
        support.removeVetoableChangeListener(param0);
    }

}
