//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-04/12/2007 12:08 AM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.24 at 01:25:15 PM PDT 
//


package com.sun.enterprise.config.serverbeans;

import org.jvnet.hk2.config.Attribute;
import org.jvnet.hk2.config.Configured;

import java.beans.PropertyVetoException;
import java.beans.VetoableChangeListener;
import java.beans.VetoableChangeSupport;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 *
 */

/* @XmlType(name = "", propOrder = {
    "ssl",
    "property"
}) */
@Configured
public class HttpListener
        implements Serializable {

	final transient private VetoableChangeSupport support = new VetoableChangeSupport(this);

    private final static long serialVersionUID = 1L;
    @Attribute(required = true)

    protected String id;
    @Attribute(required = true)

    protected String address;
    @Attribute(required = true)

    protected String port;
    @Attribute

    protected String externalPort;
    @Attribute

    protected String family;
    @Attribute

    protected String blockingEnabled;
    @Attribute

    protected String acceptorThreads;
    @Attribute

    protected String securityEnabled;
    @Attribute(required = true)

    protected String defaultVirtualServer;
    @Attribute(required = true)

    protected String serverName;
    @Attribute

    protected String redirectPort;
    @Attribute

    protected String xpoweredBy;
    @Attribute

    protected String enabled;
    protected Ssl ssl;
    protected List<Property> property = new ConstrainedList<Property>("property", support);



    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setId(String value) {
        try {
            support.fireVetoableChange("id", this.id, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.id = value;
    }

    /**
     * Gets the value of the address property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAddress(String value) {
        try {
            support.fireVetoableChange("address", this.address, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.address = value;
    }

    /**
     * Gets the value of the port property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getPort() {
        return port;
    }

    /**
     * Sets the value of the port property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPort(String value) {
        try {
            support.fireVetoableChange("port", this.port, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.port = value;
    }

    /**
     * Gets the value of the externalPort property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getExternalPort() {
        return externalPort;
    }

    /**
     * Sets the value of the externalPort property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setExternalPort(String value) {
        try {
            support.fireVetoableChange("externalPort", this.externalPort, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.externalPort = value;
    }

    /**
     * Gets the value of the family property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getFamily() {
        if (family == null) {
            return "inet";
        } else {
            return family;
        }
    }

    /**
     * Sets the value of the family property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFamily(String value) {
        try {
            support.fireVetoableChange("family", this.family, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.family = value;
    }

    /**
     * Gets the value of the blockingEnabled property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getBlockingEnabled() {
        if (blockingEnabled == null) {
            return "false";
        } else {
            return blockingEnabled;
        }
    }

    /**
     * Sets the value of the blockingEnabled property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBlockingEnabled(String value) {
        try {
            support.fireVetoableChange("blockingEnabled", this.blockingEnabled, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.blockingEnabled = value;
    }

    /**
     * Gets the value of the acceptorThreads property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getAcceptorThreads() {
        if (acceptorThreads == null) {
            return "1";
        } else {
            return acceptorThreads;
        }
    }

    /**
     * Sets the value of the acceptorThreads property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAcceptorThreads(String value) {
        try {
            support.fireVetoableChange("acceptorThreads", this.acceptorThreads, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.acceptorThreads = value;
    }

    /**
     * Gets the value of the securityEnabled property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getSecurityEnabled() {
        if (securityEnabled == null) {
            return "false";
        } else {
            return securityEnabled;
        }
    }

    /**
     * Sets the value of the securityEnabled property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSecurityEnabled(String value) {
        try {
            support.fireVetoableChange("securityEnabled", this.securityEnabled, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.securityEnabled = value;
    }

    /**
     * Gets the value of the defaultVirtualServer property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getDefaultVirtualServer() {
        return defaultVirtualServer;
    }

    /**
     * Sets the value of the defaultVirtualServer property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDefaultVirtualServer(String value) {
        try {
            support.fireVetoableChange("defaultVirtualServer", this.defaultVirtualServer, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.defaultVirtualServer = value;
    }

    /**
     * Gets the value of the serverName property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getServerName() {
        return serverName;
    }

    /**
     * Sets the value of the serverName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setServerName(String value) {
        try {
            support.fireVetoableChange("serverName", this.serverName, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.serverName = value;
    }

    /**
     * Gets the value of the redirectPort property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getRedirectPort() {
        return redirectPort;
    }

    /**
     * Sets the value of the redirectPort property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRedirectPort(String value) {
        try {
            support.fireVetoableChange("redirectPort", this.redirectPort, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.redirectPort = value;
    }

    /**
     * Gets the value of the xpoweredBy property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getXpoweredBy() {
        if (xpoweredBy == null) {
            return "true";
        } else {
            return xpoweredBy;
        }
    }

    /**
     * Sets the value of the xpoweredBy property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setXpoweredBy(String value) {
        try {
            support.fireVetoableChange("xpoweredBy", this.xpoweredBy, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.xpoweredBy = value;
    }

    /**
     * Gets the value of the enabled property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getEnabled() {
        if (enabled == null) {
            return "true";
        } else {
            return enabled;
        }
    }

    /**
     * Sets the value of the enabled property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setEnabled(String value) {
        try {
            support.fireVetoableChange("enabled", this.enabled, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.enabled = value;
    }

    /**
     * Gets the value of the ssl property.
     *
     * @return possible object is
     *         {@link Ssl }
     */
    public Ssl getSsl() {
        return ssl;
    }

    /**
     * Sets the value of the ssl property.
     *
     * @param value allowed object is
     *              {@link Ssl }
     */
    public void setSsl(Ssl value) {
        try {
            support.fireVetoableChange("ssl", this.ssl, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.ssl = value;
    }

    /**
     * Gets the value of the property property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the property property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProperty().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link Property }
     */
    public List<Property> getProperty() {

        return this.property;
    }

    public void addVetoableChangeListener(VetoableChangeListener param0) {
        support.addVetoableChangeListener(param0);
    }

    public void addVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.addVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.removeVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(VetoableChangeListener param0) {
        support.removeVetoableChangeListener(param0);
    }

}
