//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-04/12/2007 12:08 AM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.24 at 01:25:15 PM PDT 
//


package com.sun.enterprise.config.serverbeans;

import org.jvnet.hk2.config.Attribute;
import org.jvnet.hk2.config.Configured;

import java.beans.PropertyVetoException;
import java.beans.VetoableChangeListener;
import java.beans.VetoableChangeSupport;
import java.io.Serializable;


/**
 *
 */

/* @XmlType(name = "") */
@Configured
public class HttpAccessLog
        implements Serializable {

	final transient private VetoableChangeSupport support = new VetoableChangeSupport(this);

    private final static long serialVersionUID = 1L;
    @Attribute

    protected String logDirectory;
    @Attribute

    protected String iponly;



    /**
     * Gets the value of the logDirectory property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getLogDirectory() {
        if (logDirectory == null) {
            return "${com.sun.aas.instanceRoot}/logs/access";
        } else {
            return logDirectory;
        }
    }

    /**
     * Sets the value of the logDirectory property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLogDirectory(String value) {
        try {
            support.fireVetoableChange("logDirectory", this.logDirectory, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.logDirectory = value;
    }

    /**
     * Gets the value of the iponly property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getIponly() {
        if (iponly == null) {
            return "true";
        } else {
            return iponly;
        }
    }

    /**
     * Sets the value of the iponly property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIponly(String value) {
        try {
            support.fireVetoableChange("iponly", this.iponly, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.iponly = value;
    }

    public void addVetoableChangeListener(VetoableChangeListener param0) {
        support.addVetoableChangeListener(param0);
    }

    public void addVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.addVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.removeVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(VetoableChangeListener param0) {
        support.removeVetoableChangeListener(param0);
    }

}
