//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-04/12/2007 12:08 AM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.24 at 01:25:15 PM PDT 
//


package com.sun.enterprise.config.serverbeans;

import org.jvnet.hk2.config.Attribute;
import org.jvnet.hk2.config.Configured;
import org.jvnet.hk2.config.Element;

import java.beans.PropertyVetoException;
import java.beans.VetoableChangeListener;
import java.beans.VetoableChangeSupport;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 *
 */

/* @XmlType(name = "", propOrder = {
    "orb",
    "sslClientConfig",
    "iiopListener"
}) */
@Configured
public class IiopService
        implements Serializable {

	final transient private VetoableChangeSupport support = new VetoableChangeSupport(this);

    private final static long serialVersionUID = 1L;
    @Attribute

    protected String clientAuthenticationRequired;
    @Element(required=true)
    protected Orb orb;
    @Element
    protected SslClientConfig sslClientConfig;
    @Element
    protected List<IiopListener> iiopListener = new ConstrainedList<IiopListener>("iiopListener", support);



    /**
     * Gets the value of the clientAuthenticationRequired property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getClientAuthenticationRequired() {
        if (clientAuthenticationRequired == null) {
            return "false";
        } else {
            return clientAuthenticationRequired;
        }
    }

    /**
     * Sets the value of the clientAuthenticationRequired property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setClientAuthenticationRequired(String value) {
        try {
            support.fireVetoableChange("clientAuthenticationRequired", this.clientAuthenticationRequired, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.clientAuthenticationRequired = value;
    }

    /**
     * Gets the value of the orb property.
     *
     * @return possible object is
     *         {@link Orb }
     */
    public Orb getOrb() {
        return orb;
    }

    /**
     * Sets the value of the orb property.
     *
     * @param value allowed object is
     *              {@link Orb }
     */
    public void setOrb(Orb value) {
        try {
            support.fireVetoableChange("orb", this.orb, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.orb = value;
    }

    /**
     * Gets the value of the sslClientConfig property.
     *
     * @return possible object is
     *         {@link SslClientConfig }
     */
    public SslClientConfig getSslClientConfig() {
        return sslClientConfig;
    }

    /**
     * Sets the value of the sslClientConfig property.
     *
     * @param value allowed object is
     *              {@link SslClientConfig }
     */
    public void setSslClientConfig(SslClientConfig value) {
        try {
            support.fireVetoableChange("sslClientConfig", this.sslClientConfig, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.sslClientConfig = value;
    }

    /**
     * Gets the value of the iiopListener property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the iiopListener property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIiopListener().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link IiopListener }
     */
    public List<IiopListener> getIiopListener() {
        return this.iiopListener;
    }

    public void addVetoableChangeListener(VetoableChangeListener param0) {
        support.addVetoableChangeListener(param0);
    }

    public void addVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.addVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.removeVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(VetoableChangeListener param0) {
        support.removeVetoableChangeListener(param0);
    }

}
