//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-04/12/2007 12:08 AM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.24 at 01:25:15 PM PDT 
//


package com.sun.enterprise.config.serverbeans;

import org.jvnet.hk2.config.Attribute;
import org.jvnet.hk2.config.Configured;

import java.beans.PropertyVetoException;
import java.beans.VetoableChangeListener;
import java.beans.VetoableChangeSupport;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 *
 */

/* @XmlType(name = "", propOrder = {
    "description",
    "property"
}) */
@Configured
public class JdbcConnectionPool implements Resource, Serializable {

    final transient private VetoableChangeSupport support = new VetoableChangeSupport(this);
    
    private final static long serialVersionUID = 1L;
    @Attribute(required = true)

    protected String name;
    @Attribute(required = true)

    protected String datasourceClassname;
    @Attribute

    protected String resType;
    @Attribute

    protected String steadyPoolSize;
    @Attribute

    protected String maxPoolSize;
    @Attribute

    protected String maxWaitTimeInMillis;
    @Attribute

    protected String poolResizeQuantity;
    @Attribute

    protected String idleTimeoutInSeconds;
    @Attribute

    protected String transactionIsolationLevel;
    @Attribute

    protected String isIsolationLevelGuaranteed;
    @Attribute

    protected String isConnectionValidationRequired;
    @Attribute

    protected String connectionValidationMethod;
    @Attribute

    protected String validationTableName;
    @Attribute

    protected String failAllConnections;
    @Attribute

    protected String nonTransactionalConnections;
    @Attribute

    protected String allowNonComponentCallers;
    @Attribute

    protected String validateAtmostOncePeriodInSeconds;
    @Attribute

    protected String connectionLeakTimeoutInSeconds;
    @Attribute

    protected String connectionLeakReclaim;
    @Attribute

    protected String connectionCreationRetryAttempts;
    @Attribute

    protected String connectionCreationRetryIntervalInSeconds;
    @Attribute

    protected String statementTimeoutInSeconds;
    @Attribute

    protected String lazyConnectionEnlistment;
    @Attribute

    protected String lazyConnectionAssociation;
    @Attribute

    protected String associateWithThread;
    @Attribute

    protected String matchConnections;
    @Attribute

    protected String maxConnectionUsageCount;
    @Attribute

    protected String wrapJdbcObjects;
    protected String description;
    protected List<Property> property = new ConstrainedList<Property>("property", support);



    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
        try {
            support.fireVetoableChange("name", this.name, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.name = value;
    }

    /**
     * Gets the value of the datasourceClassname property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getDatasourceClassname() {
        return datasourceClassname;
    }

    /**
     * Sets the value of the datasourceClassname property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDatasourceClassname(String value) {
        try {
            support.fireVetoableChange("datasourceClassname", this.datasourceClassname, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.datasourceClassname = value;
    }

    /**
     * Gets the value of the resType property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getResType() {
        return resType;
    }

    /**
     * Sets the value of the resType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setResType(String value) {
        try {
            support.fireVetoableChange("resType", this.resType, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.resType = value;
    }

    /**
     * Gets the value of the steadyPoolSize property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getSteadyPoolSize() {
        if (steadyPoolSize == null) {
            return "8";
        } else {
            return steadyPoolSize;
        }
    }

    /**
     * Sets the value of the steadyPoolSize property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSteadyPoolSize(String value) {
        try {
            support.fireVetoableChange("steadyPoolSize", this.steadyPoolSize, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.steadyPoolSize = value;
    }

    /**
     * Gets the value of the maxPoolSize property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getMaxPoolSize() {
        if (maxPoolSize == null) {
            return "32";
        } else {
            return maxPoolSize;
        }
    }

    /**
     * Sets the value of the maxPoolSize property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMaxPoolSize(String value) {
        try {
            support.fireVetoableChange("maxPoolSize", this.maxPoolSize, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.maxPoolSize = value;
    }

    /**
     * Gets the value of the maxWaitTimeInMillis property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getMaxWaitTimeInMillis() {
        if (maxWaitTimeInMillis == null) {
            return "60000";
        } else {
            return maxWaitTimeInMillis;
        }
    }

    /**
     * Sets the value of the maxWaitTimeInMillis property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMaxWaitTimeInMillis(String value) {
        try {
            support.fireVetoableChange("maxWaitTimeInMillis", this.maxWaitTimeInMillis, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.maxWaitTimeInMillis = value;
    }

    /**
     * Gets the value of the poolResizeQuantity property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getPoolResizeQuantity() {
        if (poolResizeQuantity == null) {
            return "2";
        } else {
            return poolResizeQuantity;
        }
    }

    /**
     * Sets the value of the poolResizeQuantity property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPoolResizeQuantity(String value) {
        try {
            support.fireVetoableChange("poolResizeQuantity", this.poolResizeQuantity, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.poolResizeQuantity = value;
    }

    /**
     * Gets the value of the idleTimeoutInSeconds property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getIdleTimeoutInSeconds() {
        if (idleTimeoutInSeconds == null) {
            return "300";
        } else {
            return idleTimeoutInSeconds;
        }
    }

    /**
     * Sets the value of the idleTimeoutInSeconds property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIdleTimeoutInSeconds(String value) {
        try {
            support.fireVetoableChange("idleTimeoutInSeconds", this.idleTimeoutInSeconds, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.idleTimeoutInSeconds = value;
    }

    /**
     * Gets the value of the transactionIsolationLevel property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getTransactionIsolationLevel() {
        return transactionIsolationLevel;
    }

    /**
     * Sets the value of the transactionIsolationLevel property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTransactionIsolationLevel(String value) {
        try {
            support.fireVetoableChange("transactionIsolationLevel", this.transactionIsolationLevel, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.transactionIsolationLevel = value;
    }

    /**
     * Gets the value of the isIsolationLevelGuaranteed property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getIsIsolationLevelGuaranteed() {
        if (isIsolationLevelGuaranteed == null) {
            return "true";
        } else {
            return isIsolationLevelGuaranteed;
        }
    }

    /**
     * Sets the value of the isIsolationLevelGuaranteed property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIsIsolationLevelGuaranteed(String value) {
        try {
            support.fireVetoableChange("isIsolationLevelGuaranteed", this.isIsolationLevelGuaranteed, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.isIsolationLevelGuaranteed = value;
    }

    /**
     * Gets the value of the isConnectionValidationRequired property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getIsConnectionValidationRequired() {
        if (isConnectionValidationRequired == null) {
            return "false";
        } else {
            return isConnectionValidationRequired;
        }
    }

    /**
     * Sets the value of the isConnectionValidationRequired property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIsConnectionValidationRequired(String value) {
        try {
            support.fireVetoableChange("isConnectionValidationRequired", this.isConnectionValidationRequired, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.isConnectionValidationRequired = value;
    }

    /**
     * Gets the value of the connectionValidationMethod property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getConnectionValidationMethod() {
        if (connectionValidationMethod == null) {
            return "auto-commit";
        } else {
            return connectionValidationMethod;
        }
    }

    /**
     * Sets the value of the connectionValidationMethod property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setConnectionValidationMethod(String value) {
        try {
            support.fireVetoableChange("connectionValidationMethod", this.connectionValidationMethod, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.connectionValidationMethod = value;
    }

    /**
     * Gets the value of the validationTableName property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getValidationTableName() {
        return validationTableName;
    }

    /**
     * Sets the value of the validationTableName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setValidationTableName(String value) {
        try {
            support.fireVetoableChange("validationTableName", this.validationTableName, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.validationTableName = value;
    }

    /**
     * Gets the value of the failAllConnections property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getFailAllConnections() {
        if (failAllConnections == null) {
            return "false";
        } else {
            return failAllConnections;
        }
    }

    /**
     * Sets the value of the failAllConnections property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFailAllConnections(String value) {
        try {
            support.fireVetoableChange("failAllConnections", this.failAllConnections, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.failAllConnections = value;
    }

    /**
     * Gets the value of the nonTransactionalConnections property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getNonTransactionalConnections() {
        if (nonTransactionalConnections == null) {
            return "false";
        } else {
            return nonTransactionalConnections;
        }
    }

    /**
     * Sets the value of the nonTransactionalConnections property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setNonTransactionalConnections(String value) {
        try {
            support.fireVetoableChange("nonTransactionalConnections", this.nonTransactionalConnections, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.nonTransactionalConnections = value;
    }

    /**
     * Gets the value of the allowNonComponentCallers property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getAllowNonComponentCallers() {
        if (allowNonComponentCallers == null) {
            return "false";
        } else {
            return allowNonComponentCallers;
        }
    }

    /**
     * Sets the value of the allowNonComponentCallers property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAllowNonComponentCallers(String value) {
        try {
            support.fireVetoableChange("allowNonComponentCallers", this.allowNonComponentCallers, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.allowNonComponentCallers = value;
    }

    /**
     * Gets the value of the validateAtmostOncePeriodInSeconds property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getValidateAtmostOncePeriodInSeconds() {
        if (validateAtmostOncePeriodInSeconds == null) {
            return "0";
        } else {
            return validateAtmostOncePeriodInSeconds;
        }
    }

    /**
     * Sets the value of the validateAtmostOncePeriodInSeconds property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setValidateAtmostOncePeriodInSeconds(String value) {
        try {
            support.fireVetoableChange("validateAtmostOncePeriodInSeconds", this.validateAtmostOncePeriodInSeconds, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.validateAtmostOncePeriodInSeconds = value;
    }

    /**
     * Gets the value of the connectionLeakTimeoutInSeconds property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getConnectionLeakTimeoutInSeconds() {
        if (connectionLeakTimeoutInSeconds == null) {
            return "0";
        } else {
            return connectionLeakTimeoutInSeconds;
        }
    }

    /**
     * Sets the value of the connectionLeakTimeoutInSeconds property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setConnectionLeakTimeoutInSeconds(String value) {
        try {
            support.fireVetoableChange("connectionLeakTimeoutInSeconds", this.connectionLeakTimeoutInSeconds, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.connectionLeakTimeoutInSeconds = value;
    }

    /**
     * Gets the value of the connectionLeakReclaim property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getConnectionLeakReclaim() {
        if (connectionLeakReclaim == null) {
            return "false";
        } else {
            return connectionLeakReclaim;
        }
    }

    /**
     * Sets the value of the connectionLeakReclaim property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setConnectionLeakReclaim(String value) {
        try {
            support.fireVetoableChange("connectionLeakReclaim", this.connectionLeakReclaim, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.connectionLeakReclaim = value;
    }

    /**
     * Gets the value of the connectionCreationRetryAttempts property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getConnectionCreationRetryAttempts() {
        if (connectionCreationRetryAttempts == null) {
            return "0";
        } else {
            return connectionCreationRetryAttempts;
        }
    }

    /**
     * Sets the value of the connectionCreationRetryAttempts property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setConnectionCreationRetryAttempts(String value) {
        try {
            support.fireVetoableChange("connectionCreationRetryAttempts", this.connectionCreationRetryAttempts, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.connectionCreationRetryAttempts = value;
    }

    /**
     * Gets the value of the connectionCreationRetryIntervalInSeconds property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getConnectionCreationRetryIntervalInSeconds() {
        if (connectionCreationRetryIntervalInSeconds == null) {
            return "10";
        } else {
            return connectionCreationRetryIntervalInSeconds;
        }
    }

    /**
     * Sets the value of the connectionCreationRetryIntervalInSeconds property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setConnectionCreationRetryIntervalInSeconds(String value) {
        try {
            support.fireVetoableChange("connectionCreationRetryIntervalInSeconds", this.connectionCreationRetryIntervalInSeconds, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.connectionCreationRetryIntervalInSeconds = value;
    }

    /**
     * Gets the value of the statementTimeoutInSeconds property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getStatementTimeoutInSeconds() {
        if (statementTimeoutInSeconds == null) {
            return "-1";
        } else {
            return statementTimeoutInSeconds;
        }
    }

    /**
     * Sets the value of the statementTimeoutInSeconds property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setStatementTimeoutInSeconds(String value) {
        try {
            support.fireVetoableChange("statementTimeoutInSeconds", this.statementTimeoutInSeconds, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.statementTimeoutInSeconds = value;
    }

    /**
     * Gets the value of the lazyConnectionEnlistment property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getLazyConnectionEnlistment() {
        if (lazyConnectionEnlistment == null) {
            return "false";
        } else {
            return lazyConnectionEnlistment;
        }
    }

    /**
     * Sets the value of the lazyConnectionEnlistment property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLazyConnectionEnlistment(String value) {
        try {
            support.fireVetoableChange("lazyConnectionEnlistment", this.lazyConnectionEnlistment, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.lazyConnectionEnlistment = value;
    }

    /**
     * Gets the value of the lazyConnectionAssociation property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getLazyConnectionAssociation() {
        if (lazyConnectionAssociation == null) {
            return "false";
        } else {
            return lazyConnectionAssociation;
        }
    }

    /**
     * Sets the value of the lazyConnectionAssociation property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLazyConnectionAssociation(String value) {
        try {
            support.fireVetoableChange("lazyConnectionAssociation", this.lazyConnectionAssociation, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.lazyConnectionAssociation = value;
    }

    /**
     * Gets the value of the associateWithThread property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getAssociateWithThread() {
        if (associateWithThread == null) {
            return "false";
        } else {
            return associateWithThread;
        }
    }

    /**
     * Sets the value of the associateWithThread property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAssociateWithThread(String value) {
        try {
            support.fireVetoableChange("associateWithThread", this.associateWithThread, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.associateWithThread = value;
    }

    /**
     * Gets the value of the matchConnections property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getMatchConnections() {
        if (matchConnections == null) {
            return "false";
        } else {
            return matchConnections;
        }
    }

    /**
     * Sets the value of the matchConnections property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMatchConnections(String value) {
        try {
            support.fireVetoableChange("matchConnections", this.matchConnections, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.matchConnections = value;
    }

    /**
     * Gets the value of the maxConnectionUsageCount property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getMaxConnectionUsageCount() {
        if (maxConnectionUsageCount == null) {
            return "0";
        } else {
            return maxConnectionUsageCount;
        }
    }

    /**
     * Sets the value of the maxConnectionUsageCount property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMaxConnectionUsageCount(String value) {
        try {
            support.fireVetoableChange("maxConnectionUsageCount", this.maxConnectionUsageCount, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.maxConnectionUsageCount = value;
    }

    /**
     * Gets the value of the wrapJdbcObjects property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getWrapJdbcObjects() {
        if (wrapJdbcObjects == null) {
            return "false";
        } else {
            return wrapJdbcObjects;
        }
    }

    /**
     * Sets the value of the wrapJdbcObjects property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setWrapJdbcObjects(String value) {
        try {
            support.fireVetoableChange("wrapJdbcObjects", this.wrapJdbcObjects, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.wrapJdbcObjects = value;
    }

    /**
     * Gets the value of the description property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDescription(String value) {
        try {
            support.fireVetoableChange("description", this.description, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.description = value;
    }

    /**
     * Gets the value of the property property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the property property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProperty().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link Property }
     */
    public List<Property> getProperty() {
        return this.property;
    }

    public void addVetoableChangeListener(VetoableChangeListener param0) {
        support.addVetoableChangeListener(param0);
    }

    public void addVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.addVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.removeVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(VetoableChangeListener param0) {
        support.removeVetoableChangeListener(param0);
    }

}
