//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-04/12/2007 12:08 AM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.24 at 01:25:15 PM PDT 
//


package com.sun.enterprise.config.serverbeans;

import org.jvnet.hk2.config.Attribute;
import org.jvnet.hk2.config.Configured;
import org.jvnet.hk2.config.Element;

import java.beans.PropertyVetoException;
import java.beans.VetoableChangeListener;
import java.beans.VetoableChangeSupport;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 *
 */

/* @XmlType(name = "", propOrder = {
    "jmsHost",
    "property"
}) */
@Configured
public class JmsService
        implements Serializable {

	final transient private VetoableChangeSupport support = new VetoableChangeSupport(this);

    private final static long serialVersionUID = 1L;
    @Attribute

    protected String initTimeoutInSeconds;
    @Attribute(required = true)

    protected String type;
    @Attribute

    protected String startArgs;
    @Attribute

    protected String defaultJmsHost;
    @Attribute

    protected String reconnectIntervalInSeconds;
    @Attribute

    protected String reconnectAttempts;
    @Attribute

    protected String reconnectEnabled;
    @Attribute

    protected String addresslistBehavior;
    @Attribute

    protected String addresslistIterations;
    @Attribute

    protected String mqScheme;
    @Attribute

    protected String mqService;
    @Element
    protected List<JmsHost> jmsHost = new ConstrainedList<JmsHost>("jmsHost", support);
    protected List<Property> property = new ConstrainedList<Property>("property", support);



    /**
     * Gets the value of the initTimeoutInSeconds property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getInitTimeoutInSeconds() {
        if (initTimeoutInSeconds == null) {
            return "60";
        } else {
            return initTimeoutInSeconds;
        }
    }

    /**
     * Sets the value of the initTimeoutInSeconds property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setInitTimeoutInSeconds(String value) {
        try {
            support.fireVetoableChange("initTimeoutInSeconds", this.initTimeoutInSeconds, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.initTimeoutInSeconds = value;
    }

    /**
     * Gets the value of the type property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setType(String value) {
        try {
            support.fireVetoableChange("type", this.type, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.type = value;
    }

    /**
     * Gets the value of the startArgs property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getStartArgs() {
        return startArgs;
    }

    /**
     * Sets the value of the startArgs property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setStartArgs(String value) {
        try {
            support.fireVetoableChange("startArgs", this.startArgs, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.startArgs = value;
    }

    /**
     * Gets the value of the defaultJmsHost property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getDefaultJmsHost() {
        return defaultJmsHost;
    }

    /**
     * Sets the value of the defaultJmsHost property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDefaultJmsHost(String value) {
        try {
            support.fireVetoableChange("defaultJmsHost", this.defaultJmsHost, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.defaultJmsHost = value;
    }

    /**
     * Gets the value of the reconnectIntervalInSeconds property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getReconnectIntervalInSeconds() {
        if (reconnectIntervalInSeconds == null) {
            return "5";
        } else {
            return reconnectIntervalInSeconds;
        }
    }

    /**
     * Sets the value of the reconnectIntervalInSeconds property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setReconnectIntervalInSeconds(String value) {
        try {
            support.fireVetoableChange("reconnectIntervalInSeconds", this.reconnectIntervalInSeconds, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.reconnectIntervalInSeconds = value;
    }

    /**
     * Gets the value of the reconnectAttempts property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getReconnectAttempts() {
        if (reconnectAttempts == null) {
            return "3";
        } else {
            return reconnectAttempts;
        }
    }

    /**
     * Sets the value of the reconnectAttempts property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setReconnectAttempts(String value) {
        try {
            support.fireVetoableChange("reconnectAttempts", this.reconnectAttempts, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.reconnectAttempts = value;
    }

    /**
     * Gets the value of the reconnectEnabled property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getReconnectEnabled() {
        if (reconnectEnabled == null) {
            return "true";
        } else {
            return reconnectEnabled;
        }
    }

    /**
     * Sets the value of the reconnectEnabled property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setReconnectEnabled(String value) {
        try {
            support.fireVetoableChange("reconnectEnabled", this.reconnectEnabled, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.reconnectEnabled = value;
    }

    /**
     * Gets the value of the addresslistBehavior property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getAddresslistBehavior() {
        if (addresslistBehavior == null) {
            return "random";
        } else {
            return addresslistBehavior;
        }
    }

    /**
     * Sets the value of the addresslistBehavior property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAddresslistBehavior(String value) {
        try {
            support.fireVetoableChange("addresslistBehavior", this.addresslistBehavior, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.addresslistBehavior = value;
    }

    /**
     * Gets the value of the addresslistIterations property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getAddresslistIterations() {
        if (addresslistIterations == null) {
            return "3";
        } else {
            return addresslistIterations;
        }
    }

    /**
     * Sets the value of the addresslistIterations property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAddresslistIterations(String value) {
        try {
            support.fireVetoableChange("addresslistIterations", this.addresslistIterations, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.addresslistIterations = value;
    }

    /**
     * Gets the value of the mqScheme property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getMqScheme() {
        return mqScheme;
    }

    /**
     * Sets the value of the mqScheme property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMqScheme(String value) {
        try {
            support.fireVetoableChange("mqScheme", this.mqScheme, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.mqScheme = value;
    }

    /**
     * Gets the value of the mqService property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getMqService() {
        return mqService;
    }

    /**
     * Sets the value of the mqService property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMqService(String value) {
        try {
            support.fireVetoableChange("mqService", this.mqService, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.mqService = value;
    }

    /**
     * Gets the value of the jmsHost property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the jmsHost property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJmsHost().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link JmsHost }
     */
    public List<JmsHost> getJmsHost() {
        return this.jmsHost;
    }

    /**
     * Gets the value of the property property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the property property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProperty().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link Property }
     */
    public List<Property> getProperty() {
        return this.property;
    }

    public void addVetoableChangeListener(VetoableChangeListener param0) {
        support.addVetoableChangeListener(param0);
    }

    public void addVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.addVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.removeVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(VetoableChangeListener param0) {
        support.removeVetoableChangeListener(param0);
    }

}
