//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-04/12/2007 12:08 AM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.24 at 01:25:15 PM PDT 
//


package com.sun.enterprise.config.serverbeans;

import org.jvnet.hk2.config.Attribute;
import org.jvnet.hk2.config.Configured;

import java.beans.PropertyVetoException;
import java.beans.VetoableChangeListener;
import java.beans.VetoableChangeSupport;
import java.io.Serializable;


/**
 *
 */

/* @XmlType(name = "") */
@Configured
public class KeepAlive
        implements Serializable {

	final transient private VetoableChangeSupport support = new VetoableChangeSupport(this);

    private final static long serialVersionUID = 1L;
    @Attribute

    protected String threadCount;
    @Attribute

    protected String maxConnections;
    @Attribute

    protected String timeoutInSeconds;



    /**
     * Gets the value of the threadCount property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getThreadCount() {
        if (threadCount == null) {
            return "1";
        } else {
            return threadCount;
        }
    }

    /**
     * Sets the value of the threadCount property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setThreadCount(String value) {
        try {
            support.fireVetoableChange("threadCount", this.threadCount, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.threadCount = value;
    }

    /**
     * Gets the value of the maxConnections property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getMaxConnections() {
        if (maxConnections == null) {
            return "256";
        } else {
            return maxConnections;
        }
    }

    /**
     * Sets the value of the maxConnections property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMaxConnections(String value) {
        try {
            support.fireVetoableChange("maxConnections", this.maxConnections, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.maxConnections = value;
    }

    /**
     * Gets the value of the timeoutInSeconds property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getTimeoutInSeconds() {
        if (timeoutInSeconds == null) {
            return "30";
        } else {
            return timeoutInSeconds;
        }
    }

    /**
     * Sets the value of the timeoutInSeconds property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTimeoutInSeconds(String value) {
        try {
            support.fireVetoableChange("timeoutInSeconds", this.timeoutInSeconds, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.timeoutInSeconds = value;
    }

    public void addVetoableChangeListener(VetoableChangeListener param0) {
        support.addVetoableChangeListener(param0);
    }

    public void addVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.addVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.removeVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(VetoableChangeListener param0) {
        support.removeVetoableChangeListener(param0);
    }

}
