//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-04/12/2007 12:08 AM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.24 at 01:25:15 PM PDT 
//


package com.sun.enterprise.config.serverbeans;

import org.jvnet.hk2.config.Attribute;
import org.jvnet.hk2.config.Configured;
import org.jvnet.hk2.config.Element;

import java.beans.PropertyVetoException;
import java.beans.VetoableChangeListener;
import java.beans.VetoableChangeSupport;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 *
 */

/* @XmlType(name = "", propOrder = {
    "providerConfig"
}) */
@Configured
public class MessageSecurityConfig
        implements Serializable {

	final transient private VetoableChangeSupport support = new VetoableChangeSupport(this);

    private final static long serialVersionUID = 1L;
    @Attribute(required = true)

    protected String authLayer;
    @Attribute

    protected String defaultProvider;
    @Attribute

    protected String defaultClientProvider;
    @Element(required=true)
    protected List<ProviderConfig> providerConfig = new ConstrainedList<ProviderConfig>("providerConfig", support);



    /**
     * Gets the value of the authLayer property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getAuthLayer() {
        return authLayer;
    }

    /**
     * Sets the value of the authLayer property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAuthLayer(String value) {
        try {
            support.fireVetoableChange("authLayer", this.authLayer, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.authLayer = value;
    }

    /**
     * Gets the value of the defaultProvider property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getDefaultProvider() {
        return defaultProvider;
    }

    /**
     * Sets the value of the defaultProvider property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDefaultProvider(String value) {
        try {
            support.fireVetoableChange("defaultProvider", this.defaultProvider, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.defaultProvider = value;
    }

    /**
     * Gets the value of the defaultClientProvider property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getDefaultClientProvider() {
        return defaultClientProvider;
    }

    /**
     * Sets the value of the defaultClientProvider property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDefaultClientProvider(String value) {
        try {
            support.fireVetoableChange("defaultClientProvider", this.defaultClientProvider, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.defaultClientProvider = value;
    }

    /**
     * Gets the value of the providerConfig property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the providerConfig property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProviderConfig().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link ProviderConfig }
     */
    public List<ProviderConfig> getProviderConfig() {
        return this.providerConfig;
    }

    public void addVetoableChangeListener(VetoableChangeListener param0) {
        support.addVetoableChangeListener(param0);
    }

    public void addVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.addVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.removeVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(VetoableChangeListener param0) {
        support.removeVetoableChangeListener(param0);
    }

}
