//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-04/12/2007 12:08 AM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.24 at 01:25:15 PM PDT 
//


package com.sun.enterprise.config.serverbeans;

import org.jvnet.hk2.config.Attribute;
import org.jvnet.hk2.config.Configured;

import java.beans.PropertyVetoException;
import java.beans.VetoableChangeListener;
import java.beans.VetoableChangeSupport;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 *
 */

/* @XmlType(name = "", propOrder = {
    "property"
}) */
@Configured
public class ModuleLogLevels
        implements Serializable {

	final transient private VetoableChangeSupport support = new VetoableChangeSupport(this);

    private final static long serialVersionUID = 1L;
    @Attribute

    protected String root;
    @Attribute

    protected String server;
    @Attribute

    protected String ejbContainer;
    @Attribute

    protected String cmpContainer;
    @Attribute

    protected String mdbContainer;
    @Attribute

    protected String webContainer;
    @Attribute

    protected String classloader;
    @Attribute

    protected String configuration;
    @Attribute

    protected String naming;
    @Attribute

    protected String security;
    @Attribute

    protected String jts;
    @Attribute

    protected String jta;
    @Attribute

    protected String admin;
    @Attribute

    protected String deployment;
    @Attribute

    protected String verifier;
    @Attribute

    protected String jaxr;
    @Attribute

    protected String jaxrpc;
    @Attribute

    protected String saaj;
    @Attribute

    protected String corba;
    @Attribute

    protected String javamail;
    @Attribute

    protected String jms;
    @Attribute

    protected String connector;
    @Attribute

    protected String jdo;
    @Attribute

    protected String cmp;
    @Attribute

    protected String util;
    @Attribute

    protected String resourceAdapter;
    @Attribute

    protected String synchronization;
    @Attribute

    protected String nodeAgent;
    @Attribute

    protected String selfManagement;
    @Attribute

    protected String groupManagementService;
    @Attribute

    protected String managementEvent;
    protected List<Property> property = new ConstrainedList<Property>("property", support);



    /**
     * Gets the value of the root property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getRoot() {
        if (root == null) {
            return "INFO";
        } else {
            return root;
        }
    }

    /**
     * Sets the value of the root property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRoot(String value) {
        try {
            support.fireVetoableChange("root", this.root, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.root = value;
    }

    /**
     * Gets the value of the server property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getServer() {
        if (server == null) {
            return "INFO";
        } else {
            return server;
        }
    }

    /**
     * Sets the value of the server property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setServer(String value) {
        try {
            support.fireVetoableChange("server", this.server, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.server = value;
    }

    /**
     * Gets the value of the ejbContainer property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getEjbContainer() {
        if (ejbContainer == null) {
            return "INFO";
        } else {
            return ejbContainer;
        }
    }

    /**
     * Sets the value of the ejbContainer property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setEjbContainer(String value) {
        try {
            support.fireVetoableChange("ejbContainer", this.ejbContainer, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.ejbContainer = value;
    }

    /**
     * Gets the value of the cmpContainer property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getCmpContainer() {
        if (cmpContainer == null) {
            return "INFO";
        } else {
            return cmpContainer;
        }
    }

    /**
     * Sets the value of the cmpContainer property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCmpContainer(String value) {
        try {
            support.fireVetoableChange("cmpContainer", this.cmpContainer, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.cmpContainer = value;
    }

    /**
     * Gets the value of the mdbContainer property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getMdbContainer() {
        if (mdbContainer == null) {
            return "INFO";
        } else {
            return mdbContainer;
        }
    }

    /**
     * Sets the value of the mdbContainer property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMdbContainer(String value) {
        try {
            support.fireVetoableChange("mdbContainer", this.mdbContainer, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.mdbContainer = value;
    }

    /**
     * Gets the value of the webContainer property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getWebContainer() {
        if (webContainer == null) {
            return "INFO";
        } else {
            return webContainer;
        }
    }

    /**
     * Sets the value of the webContainer property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setWebContainer(String value) {
        try {
            support.fireVetoableChange("webContainer", this.webContainer, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.webContainer = value;
    }

    /**
     * Gets the value of the classloader property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getClassloader() {
        if (classloader == null) {
            return "INFO";
        } else {
            return classloader;
        }
    }

    /**
     * Sets the value of the classloader property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setClassloader(String value) {
        try {
            support.fireVetoableChange("classloader", this.classloader, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.classloader = value;
    }

    /**
     * Gets the value of the configuration property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getConfiguration() {
        if (configuration == null) {
            return "INFO";
        } else {
            return configuration;
        }
    }

    /**
     * Sets the value of the configuration property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setConfiguration(String value) {
        try {
            support.fireVetoableChange("configuration", this.configuration, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.configuration = value;
    }

    /**
     * Gets the value of the naming property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getNaming() {
        if (naming == null) {
            return "INFO";
        } else {
            return naming;
        }
    }

    /**
     * Sets the value of the naming property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setNaming(String value) {
        try {
            support.fireVetoableChange("naming", this.naming, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.naming = value;
    }

    /**
     * Gets the value of the security property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getSecurity() {
        if (security == null) {
            return "INFO";
        } else {
            return security;
        }
    }

    /**
     * Sets the value of the security property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSecurity(String value) {
        try {
            support.fireVetoableChange("security", this.security, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.security = value;
    }

    /**
     * Gets the value of the jts property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getJts() {
        if (jts == null) {
            return "INFO";
        } else {
            return jts;
        }
    }

    /**
     * Sets the value of the jts property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setJts(String value) {
        try {
            support.fireVetoableChange("jts", this.jts, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.jts = value;
    }

    /**
     * Gets the value of the jta property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getJta() {
        if (jta == null) {
            return "INFO";
        } else {
            return jta;
        }
    }

    /**
     * Sets the value of the jta property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setJta(String value) {
        try {
            support.fireVetoableChange("jta", this.jta, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.jta = value;
    }

    /**
     * Gets the value of the admin property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getAdmin() {
        if (admin == null) {
            return "INFO";
        } else {
            return admin;
        }
    }

    /**
     * Sets the value of the admin property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAdmin(String value) {
        try {
            support.fireVetoableChange("admin", this.admin, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.admin = value;
    }

    /**
     * Gets the value of the deployment property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getDeployment() {
        if (deployment == null) {
            return "INFO";
        } else {
            return deployment;
        }
    }

    /**
     * Sets the value of the deployment property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDeployment(String value) {
        try {
            support.fireVetoableChange("deployment", this.deployment, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.deployment = value;
    }

    /**
     * Gets the value of the verifier property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getVerifier() {
        if (verifier == null) {
            return "INFO";
        } else {
            return verifier;
        }
    }

    /**
     * Sets the value of the verifier property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setVerifier(String value) {
        try {
            support.fireVetoableChange("verifier", this.verifier, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.verifier = value;
    }

    /**
     * Gets the value of the jaxr property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getJaxr() {
        if (jaxr == null) {
            return "INFO";
        } else {
            return jaxr;
        }
    }

    /**
     * Sets the value of the jaxr property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setJaxr(String value) {
        try {
            support.fireVetoableChange("jaxr", this.jaxr, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.jaxr = value;
    }

    /**
     * Gets the value of the jaxrpc property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getJaxrpc() {
        if (jaxrpc == null) {
            return "INFO";
        } else {
            return jaxrpc;
        }
    }

    /**
     * Sets the value of the jaxrpc property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setJaxrpc(String value) {
        try {
            support.fireVetoableChange("jaxrpc", this.jaxrpc, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.jaxrpc = value;
    }

    /**
     * Gets the value of the saaj property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getSaaj() {
        if (saaj == null) {
            return "INFO";
        } else {
            return saaj;
        }
    }

    /**
     * Sets the value of the saaj property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSaaj(String value) {
        try {
            support.fireVetoableChange("saaj", this.saaj, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.saaj = value;
    }

    /**
     * Gets the value of the corba property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getCorba() {
        if (corba == null) {
            return "INFO";
        } else {
            return corba;
        }
    }

    /**
     * Sets the value of the corba property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCorba(String value) {
        try {
            support.fireVetoableChange("corba", this.corba, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.corba = value;
    }

    /**
     * Gets the value of the javamail property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getJavamail() {
        if (javamail == null) {
            return "INFO";
        } else {
            return javamail;
        }
    }

    /**
     * Sets the value of the javamail property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setJavamail(String value) {
        try {
            support.fireVetoableChange("javamail", this.javamail, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.javamail = value;
    }

    /**
     * Gets the value of the jms property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getJms() {
        if (jms == null) {
            return "INFO";
        } else {
            return jms;
        }
    }

    /**
     * Sets the value of the jms property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setJms(String value) {
        try {
            support.fireVetoableChange("jms", this.jms, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.jms = value;
    }

    /**
     * Gets the value of the connector property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getConnector() {
        if (connector == null) {
            return "INFO";
        } else {
            return connector;
        }
    }

    /**
     * Sets the value of the connector property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setConnector(String value) {
        try {
            support.fireVetoableChange("connector", this.connector, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.connector = value;
    }

    /**
     * Gets the value of the jdo property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getJdo() {
        if (jdo == null) {
            return "INFO";
        } else {
            return jdo;
        }
    }

    /**
     * Sets the value of the jdo property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setJdo(String value) {
        try {
            support.fireVetoableChange("jdo", this.jdo, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.jdo = value;
    }

    /**
     * Gets the value of the cmp property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getCmp() {
        if (cmp == null) {
            return "INFO";
        } else {
            return cmp;
        }
    }

    /**
     * Sets the value of the cmp property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCmp(String value) {
        try {
            support.fireVetoableChange("cmp", this.cmp, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.cmp = value;
    }

    /**
     * Gets the value of the util property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getUtil() {
        if (util == null) {
            return "INFO";
        } else {
            return util;
        }
    }

    /**
     * Sets the value of the util property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setUtil(String value) {
        try {
            support.fireVetoableChange("util", this.util, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.util = value;
    }

    /**
     * Gets the value of the resourceAdapter property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getResourceAdapter() {
        if (resourceAdapter == null) {
            return "INFO";
        } else {
            return resourceAdapter;
        }
    }

    /**
     * Sets the value of the resourceAdapter property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setResourceAdapter(String value) {
        try {
            support.fireVetoableChange("resourceAdapter", this.resourceAdapter, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.resourceAdapter = value;
    }

    /**
     * Gets the value of the synchronization property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getSynchronization() {
        if (synchronization == null) {
            return "INFO";
        } else {
            return synchronization;
        }
    }

    /**
     * Sets the value of the synchronization property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSynchronization(String value) {
        try {
            support.fireVetoableChange("synchronization", this.synchronization, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.synchronization = value;
    }

    /**
     * Gets the value of the nodeAgent property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getNodeAgent() {
        if (nodeAgent == null) {
            return "INFO";
        } else {
            return nodeAgent;
        }
    }

    /**
     * Sets the value of the nodeAgent property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setNodeAgent(String value) {
        try {
            support.fireVetoableChange("nodeAgent", this.nodeAgent, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.nodeAgent = value;
    }

    /**
     * Gets the value of the selfManagement property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getSelfManagement() {
        if (selfManagement == null) {
            return "INFO";
        } else {
            return selfManagement;
        }
    }

    /**
     * Sets the value of the selfManagement property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSelfManagement(String value) {
        try {
            support.fireVetoableChange("selfManagement", this.selfManagement, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.selfManagement = value;
    }

    /**
     * Gets the value of the groupManagementService property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getGroupManagementService() {
        if (groupManagementService == null) {
            return "INFO";
        } else {
            return groupManagementService;
        }
    }

    /**
     * Sets the value of the groupManagementService property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setGroupManagementService(String value) {
        try {
            support.fireVetoableChange("groupManagementService", this.groupManagementService, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.groupManagementService = value;
    }

    /**
     * Gets the value of the managementEvent property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getManagementEvent() {
        if (managementEvent == null) {
            return "INFO";
        } else {
            return managementEvent;
        }
    }

    /**
     * Sets the value of the managementEvent property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setManagementEvent(String value) {
        try {
            support.fireVetoableChange("managementEvent", this.managementEvent, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.managementEvent = value;
    }

    /**
     * Gets the value of the property property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the property property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProperty().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link Property }
     */
    public List<Property> getProperty() {
        return this.property;
    }

    public void addVetoableChangeListener(VetoableChangeListener param0) {
        support.addVetoableChangeListener(param0);
    }

    public void addVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.addVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.removeVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(VetoableChangeListener param0) {
        support.removeVetoableChangeListener(param0);
    }

}
