//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-04/12/2007 12:08 AM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.24 at 01:25:15 PM PDT 
//


package com.sun.enterprise.config.serverbeans;

import org.jvnet.hk2.config.Attribute;
import org.jvnet.hk2.config.Configured;

import java.beans.PropertyVetoException;
import java.beans.VetoableChangeListener;
import java.beans.VetoableChangeSupport;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 *
 */

/* @XmlType(name = "", propOrder = {
    "property"
}) */
@Configured
public class ModuleMonitoringLevels
        implements Serializable {

	final transient private VetoableChangeSupport support = new VetoableChangeSupport(this);

    private final static long serialVersionUID = 1L;
    @Attribute

    protected String threadPool;
    @Attribute

    protected String orb;
    @Attribute

    protected String ejbContainer;
    @Attribute

    protected String webContainer;
    @Attribute

    protected String transactionService;
    @Attribute

    protected String httpService;
    @Attribute

    protected String jdbcConnectionPool;
    @Attribute

    protected String connectorConnectionPool;
    @Attribute

    protected String connectorService;
    @Attribute

    protected String jmsService;
    @Attribute

    protected String jvm;
    protected List<Property> property = new ConstrainedList<Property>("property", support);



    /**
     * Gets the value of the threadPool property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getThreadPool() {
        if (threadPool == null) {
            return "OFF";
        } else {
            return threadPool;
        }
    }

    /**
     * Sets the value of the threadPool property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setThreadPool(String value) {
        try {
            support.fireVetoableChange("threadPool", this.threadPool, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.threadPool = value;
    }

    /**
     * Gets the value of the orb property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getOrb() {
        if (orb == null) {
            return "OFF";
        } else {
            return orb;
        }
    }

    /**
     * Sets the value of the orb property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOrb(String value) {
        try {
            support.fireVetoableChange("orb", this.orb, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.orb = value;
    }

    /**
     * Gets the value of the ejbContainer property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getEjbContainer() {
        if (ejbContainer == null) {
            return "OFF";
        } else {
            return ejbContainer;
        }
    }

    /**
     * Sets the value of the ejbContainer property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setEjbContainer(String value) {
        try {
            support.fireVetoableChange("ejbContainer", this.ejbContainer, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.ejbContainer = value;
    }

    /**
     * Gets the value of the webContainer property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getWebContainer() {
        if (webContainer == null) {
            return "OFF";
        } else {
            return webContainer;
        }
    }

    /**
     * Sets the value of the webContainer property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setWebContainer(String value) {
        try {
            support.fireVetoableChange("webContainer", this.webContainer, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.webContainer = value;
    }

    /**
     * Gets the value of the transactionService property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getTransactionService() {
        if (transactionService == null) {
            return "OFF";
        } else {
            return transactionService;
        }
    }

    /**
     * Sets the value of the transactionService property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTransactionService(String value) {
        try {
            support.fireVetoableChange("transactionService", this.transactionService, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.transactionService = value;
    }

    /**
     * Gets the value of the httpService property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getHttpService() {
        if (httpService == null) {
            return "OFF";
        } else {
            return httpService;
        }
    }

    /**
     * Sets the value of the httpService property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setHttpService(String value) {
        try {
            support.fireVetoableChange("httpService", this.httpService, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.httpService = value;
    }

    /**
     * Gets the value of the jdbcConnectionPool property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getJdbcConnectionPool() {
        if (jdbcConnectionPool == null) {
            return "OFF";
        } else {
            return jdbcConnectionPool;
        }
    }

    /**
     * Sets the value of the jdbcConnectionPool property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setJdbcConnectionPool(String value) {
        try {
            support.fireVetoableChange("jdbcConnectionPool", this.jdbcConnectionPool, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.jdbcConnectionPool = value;
    }

    /**
     * Gets the value of the connectorConnectionPool property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getConnectorConnectionPool() {
        if (connectorConnectionPool == null) {
            return "OFF";
        } else {
            return connectorConnectionPool;
        }
    }

    /**
     * Sets the value of the connectorConnectionPool property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setConnectorConnectionPool(String value) {
        try {
            support.fireVetoableChange("connectorConnectionPool", this.connectorConnectionPool, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.connectorConnectionPool = value;
    }

    /**
     * Gets the value of the connectorService property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getConnectorService() {
        if (connectorService == null) {
            return "OFF";
        } else {
            return connectorService;
        }
    }

    /**
     * Sets the value of the connectorService property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setConnectorService(String value) {
        try {
            support.fireVetoableChange("connectorService", this.connectorService, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.connectorService = value;
    }

    /**
     * Gets the value of the jmsService property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getJmsService() {
        if (jmsService == null) {
            return "OFF";
        } else {
            return jmsService;
        }
    }

    /**
     * Sets the value of the jmsService property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setJmsService(String value) {
        try {
            support.fireVetoableChange("jmsService", this.jmsService, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.jmsService = value;
    }

    /**
     * Gets the value of the jvm property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getJvm() {
        if (jvm == null) {
            return "OFF";
        } else {
            return jvm;
        }
    }

    /**
     * Sets the value of the jvm property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setJvm(String value) {
        try {
            support.fireVetoableChange("jvm", this.jvm, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.jvm = value;
    }

    /**
     * Gets the value of the property property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the property property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProperty().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link Property }
     */
    public List<Property> getProperty() {
        return this.property;
    }

    public void addVetoableChangeListener(VetoableChangeListener param0) {
        support.addVetoableChangeListener(param0);
    }

    public void addVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.addVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.removeVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(VetoableChangeListener param0) {
        support.removeVetoableChangeListener(param0);
    }

}
