//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-04/12/2007 12:08 AM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.24 at 01:25:15 PM PDT 
//


package com.sun.enterprise.config.serverbeans;

import org.jvnet.hk2.config.Attribute;
import org.jvnet.hk2.config.Configured;
import org.jvnet.hk2.config.Element;

import java.beans.PropertyVetoException;
import java.beans.VetoableChangeListener;
import java.beans.VetoableChangeSupport;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 *
 */

/* @XmlType(name = "", propOrder = {
    "jmxConnector",
    "authRealm",
    "logService",
    "property"
}) */
@Configured
public class NodeAgent
        implements Serializable {

	final transient private VetoableChangeSupport support = new VetoableChangeSupport(this);

    private final static long serialVersionUID = 1L;
    @Attribute(required = true)

    protected String name;
    @Attribute

    protected String systemJmxConnectorName;
    @Attribute

    protected String startServersInStartup;
    @Element
    protected JmxConnector jmxConnector;
    @Element
    protected AuthRealm authRealm;
    @Element(required=true)
    protected LogService logService;
    protected List<Property> property = new ConstrainedList<Property>("property", support);



    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
        try {
            support.fireVetoableChange("name", this.name, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.name = value;
    }

    /**
     * Gets the value of the systemJmxConnectorName property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getSystemJmxConnectorName() {
        return systemJmxConnectorName;
    }

    /**
     * Sets the value of the systemJmxConnectorName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSystemJmxConnectorName(String value) {
        try {
            support.fireVetoableChange("systemJmxConnectorName", this.systemJmxConnectorName, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.systemJmxConnectorName = value;
    }

    /**
     * Gets the value of the startServersInStartup property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getStartServersInStartup() {
        if (startServersInStartup == null) {
            return "true";
        } else {
            return startServersInStartup;
        }
    }

    /**
     * Sets the value of the startServersInStartup property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setStartServersInStartup(String value) {
        try {
            support.fireVetoableChange("startServersInStartup", this.startServersInStartup, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.startServersInStartup = value;
    }

    /**
     * Gets the value of the jmxConnector property.
     *
     * @return possible object is
     *         {@link JmxConnector }
     */
    public JmxConnector getJmxConnector() {
        return jmxConnector;
    }

    /**
     * Sets the value of the jmxConnector property.
     *
     * @param value allowed object is
     *              {@link JmxConnector }
     */
    public void setJmxConnector(JmxConnector value) {
        try {
            support.fireVetoableChange("jmxConnector", this.jmxConnector, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.jmxConnector = value;
    }

    /**
     * Gets the value of the authRealm property.
     *
     * @return possible object is
     *         {@link AuthRealm }
     */
    public AuthRealm getAuthRealm() {
        return authRealm;
    }

    /**
     * Sets the value of the authRealm property.
     *
     * @param value allowed object is
     *              {@link AuthRealm }
     */
    public void setAuthRealm(AuthRealm value) {
        try {
            support.fireVetoableChange("authRealm", this.authRealm, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.authRealm = value;
    }

    /**
     * Gets the value of the logService property.
     *
     * @return possible object is
     *         {@link LogService }
     */
    public LogService getLogService() {
        return logService;
    }

    /**
     * Sets the value of the logService property.
     *
     * @param value allowed object is
     *              {@link LogService }
     */
    public void setLogService(LogService value) {
        try {
            support.fireVetoableChange("logService", this.logService, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.logService = value;
    }

    /**
     * Gets the value of the property property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the property property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProperty().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link Property }
     */
    public List<Property> getProperty() {
        return this.property;
    }

    public void addVetoableChangeListener(VetoableChangeListener param0) {
        support.addVetoableChangeListener(param0);
    }

    public void addVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.addVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.removeVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(VetoableChangeListener param0) {
        support.removeVetoableChangeListener(param0);
    }

}
