//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-04/12/2007 12:08 AM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.24 at 01:25:15 PM PDT 
//


package com.sun.enterprise.config.serverbeans;

import org.jvnet.hk2.config.Attribute;
import org.jvnet.hk2.config.Configured;

import java.beans.PropertyVetoException;
import java.beans.VetoableChangeListener;
import java.beans.VetoableChangeSupport;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 *
 */

/* @XmlType(name = "", propOrder = {
    "property"
}) */
@Configured
public class Orb
        implements Serializable {

	final transient private VetoableChangeSupport support = new VetoableChangeSupport(this);

    private final static long serialVersionUID = 1L;
    @Attribute(required = true)

    protected String useThreadPoolIds;
    @Attribute

    protected String messageFragmentSize;
    @Attribute

    protected String maxConnections;
    protected List<Property> property = new ConstrainedList<Property>("property", support);



    /**
     * Gets the value of the useThreadPoolIds property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getUseThreadPoolIds() {
        return useThreadPoolIds;
    }

    /**
     * Sets the value of the useThreadPoolIds property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setUseThreadPoolIds(String value) {
        try {
            support.fireVetoableChange("useThreadPoolIds", this.useThreadPoolIds, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.useThreadPoolIds = value;
    }

    /**
     * Gets the value of the messageFragmentSize property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getMessageFragmentSize() {
        if (messageFragmentSize == null) {
            return "1024";
        } else {
            return messageFragmentSize;
        }
    }

    /**
     * Sets the value of the messageFragmentSize property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMessageFragmentSize(String value) {
        try {
            support.fireVetoableChange("messageFragmentSize", this.messageFragmentSize, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.messageFragmentSize = value;
    }

    /**
     * Gets the value of the maxConnections property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getMaxConnections() {
        if (maxConnections == null) {
            return "1024";
        } else {
            return maxConnections;
        }
    }

    /**
     * Sets the value of the maxConnections property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMaxConnections(String value) {
        try {
            support.fireVetoableChange("maxConnections", this.maxConnections, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.maxConnections = value;
    }

    /**
     * Gets the value of the property property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the property property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProperty().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link Property }
     */
    public List<Property> getProperty() {
        return this.property;
    }

    public void addVetoableChangeListener(VetoableChangeListener param0) {
        support.addVetoableChangeListener(param0);
    }

    public void addVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.addVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.removeVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(VetoableChangeListener param0) {
        support.removeVetoableChangeListener(param0);
    }

}
