//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-04/12/2007 12:08 AM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.24 at 01:25:15 PM PDT 
//


package com.sun.enterprise.config.serverbeans;

import org.jvnet.hk2.config.Attribute;
import org.jvnet.hk2.config.Configured;
import org.jvnet.hk2.config.Element;

import java.beans.PropertyVetoException;
import java.beans.VetoableChangeListener;
import java.beans.VetoableChangeSupport;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 *
 */

/* @XmlType(name = "", propOrder = {
    "requestPolicy",
    "responsePolicy",
    "property"
}) */
@Configured
public class ProviderConfig
        implements Serializable {

	final transient private VetoableChangeSupport support = new VetoableChangeSupport(this);

    private final static long serialVersionUID = 1L;
    @Attribute(required = true)

    protected String providerId;
    @Attribute(required = true)

    protected String providerType;
    @Attribute(required = true)

    protected String className;
    @Element
    protected RequestPolicy requestPolicy;
    @Element
    protected ResponsePolicy responsePolicy;
    protected List<Property> property = new ConstrainedList<Property>("property", support);



    /**
     * Gets the value of the providerId property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getProviderId() {
        return providerId;
    }

    /**
     * Sets the value of the providerId property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setProviderId(String value) {
        try {
            support.fireVetoableChange("providerId", this.providerId, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.providerId = value;
    }

    /**
     * Gets the value of the providerType property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getProviderType() {
        return providerType;
    }

    /**
     * Sets the value of the providerType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setProviderType(String value) {
        try {
            support.fireVetoableChange("providerType", this.providerType, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.providerType = value;
    }

    /**
     * Gets the value of the className property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getClassName() {
        return className;
    }

    /**
     * Sets the value of the className property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setClassName(String value) {
        try {
            support.fireVetoableChange("className", this.className, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.className = value;
    }

    /**
     * Gets the value of the requestPolicy property.
     *
     * @return possible object is
     *         {@link RequestPolicy }
     */
    public RequestPolicy getRequestPolicy() {
        return requestPolicy;
    }

    /**
     * Sets the value of the requestPolicy property.
     *
     * @param value allowed object is
     *              {@link RequestPolicy }
     */
    public void setRequestPolicy(RequestPolicy value) {
        try {
            support.fireVetoableChange("requestPolicy", this.requestPolicy, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.requestPolicy = value;
    }

    /**
     * Gets the value of the responsePolicy property.
     *
     * @return possible object is
     *         {@link ResponsePolicy }
     */
    public ResponsePolicy getResponsePolicy() {
        return responsePolicy;
    }

    /**
     * Sets the value of the responsePolicy property.
     *
     * @param value allowed object is
     *              {@link ResponsePolicy }
     */
    public void setResponsePolicy(ResponsePolicy value) {
        try {
            support.fireVetoableChange("responsePolicy", this.responsePolicy, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.responsePolicy = value;
    }

    /**
     * Gets the value of the property property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the property property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProperty().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link Property }
     */
    public List<Property> getProperty() {
        return this.property;
    }

    public void addVetoableChangeListener(VetoableChangeListener param0) {
        support.addVetoableChangeListener(param0);
    }

    public void addVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.addVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.removeVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(VetoableChangeListener param0) {
        support.removeVetoableChangeListener(param0);
    }

}
