//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-04/12/2007 12:08 AM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.24 at 01:25:15 PM PDT 
//


package com.sun.enterprise.config.serverbeans;

import org.jvnet.hk2.config.Attribute;
import org.jvnet.hk2.config.Configured;
import org.jvnet.hk2.config.Element;

import java.beans.PropertyVetoException;
import java.beans.VetoableChangeListener;
import java.beans.VetoableChangeSupport;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 *
 */

/* @XmlType(name = "", propOrder = {
    "authRealm",
    "jaccProvider",
    "auditModule",
    "messageSecurityConfig",
    "property"
}) */
@Configured
public class SecurityService
        implements Serializable {

	final transient private VetoableChangeSupport support = new VetoableChangeSupport(this);

    private final static long serialVersionUID = 1L;
    @Attribute

    protected String defaultRealm;
    @Attribute

    protected String defaultPrincipal;
    @Attribute

    protected String defaultPrincipalPassword;
    @Attribute

    protected String anonymousRole;
    @Attribute

    protected String auditEnabled;
    @Attribute

    protected String jacc;
    @Attribute

    protected String auditModules;
    @Attribute

    protected String activateDefaultPrincipalToRoleMapping;
    @Attribute

    protected String mappedPrincipalClass;
    @Element(required=true)
    protected List<AuthRealm> authRealm = new ConstrainedList<AuthRealm>("authRealm", support);
    @Element(required=true)
    protected List<JaccProvider> jaccProvider = new ConstrainedList<JaccProvider>("jaccProvider", support);
    @Element
    protected List<AuditModule> auditModule = new ConstrainedList<AuditModule>("auditModule", support);
    @Element
    protected List<MessageSecurityConfig> messageSecurityConfig = new ConstrainedList<MessageSecurityConfig>("messageSecurityConfig", support);
    protected List<Property> property = new ConstrainedList<Property>("property", support);



    /**
     * Gets the value of the defaultRealm property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getDefaultRealm() {
        if (defaultRealm == null) {
            return "file";
        } else {
            return defaultRealm;
        }
    }

    /**
     * Sets the value of the defaultRealm property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDefaultRealm(String value) {
        try {
            support.fireVetoableChange("defaultRealm", this.defaultRealm, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.defaultRealm = value;
    }

    /**
     * Gets the value of the defaultPrincipal property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getDefaultPrincipal() {
        return defaultPrincipal;
    }

    /**
     * Sets the value of the defaultPrincipal property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDefaultPrincipal(String value) {
        try {
            support.fireVetoableChange("defaultPrincipal", this.defaultPrincipal, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.defaultPrincipal = value;
    }

    /**
     * Gets the value of the defaultPrincipalPassword property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getDefaultPrincipalPassword() {
        return defaultPrincipalPassword;
    }

    /**
     * Sets the value of the defaultPrincipalPassword property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDefaultPrincipalPassword(String value) {
        try {
            support.fireVetoableChange("defaultPrincipalPassword", this.defaultPrincipalPassword, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.defaultPrincipalPassword = value;
    }

    /**
     * Gets the value of the anonymousRole property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getAnonymousRole() {
        if (anonymousRole == null) {
            return "AttributeDeprecated";
        } else {
            return anonymousRole;
        }
    }

    /**
     * Sets the value of the anonymousRole property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAnonymousRole(String value) {
        try {
            support.fireVetoableChange("anonymousRole", this.anonymousRole, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.anonymousRole = value;
    }

    /**
     * Gets the value of the auditEnabled property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getAuditEnabled() {
        if (auditEnabled == null) {
            return "false";
        } else {
            return auditEnabled;
        }
    }

    /**
     * Sets the value of the auditEnabled property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAuditEnabled(String value) {
        try {
            support.fireVetoableChange("auditEnabled", this.auditEnabled, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.auditEnabled = value;
    }

    /**
     * Gets the value of the jacc property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getJacc() {
        if (jacc == null) {
            return "default";
        } else {
            return jacc;
        }
    }

    /**
     * Sets the value of the jacc property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setJacc(String value) {
        try {
            support.fireVetoableChange("jacc", this.jacc, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.jacc = value;
    }

    /**
     * Gets the value of the auditModules property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getAuditModules() {
        if (auditModules == null) {
            return "default";
        } else {
            return auditModules;
        }
    }

    /**
     * Sets the value of the auditModules property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAuditModules(String value) {
        try {
            support.fireVetoableChange("auditModules", this.auditModules, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.auditModules = value;
    }

    /**
     * Gets the value of the activateDefaultPrincipalToRoleMapping property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getActivateDefaultPrincipalToRoleMapping() {
        if (activateDefaultPrincipalToRoleMapping == null) {
            return "false";
        } else {
            return activateDefaultPrincipalToRoleMapping;
        }
    }

    /**
     * Sets the value of the activateDefaultPrincipalToRoleMapping property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setActivateDefaultPrincipalToRoleMapping(String value) {
        try {
            support.fireVetoableChange("activateDefaultPrincipalToRoleMapping", this.activateDefaultPrincipalToRoleMapping, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.activateDefaultPrincipalToRoleMapping = value;
    }

    /**
     * Gets the value of the mappedPrincipalClass property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getMappedPrincipalClass() {
        return mappedPrincipalClass;
    }

    /**
     * Sets the value of the mappedPrincipalClass property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMappedPrincipalClass(String value) {
        try {
            support.fireVetoableChange("mappedPrincipalClass", this.mappedPrincipalClass, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.mappedPrincipalClass = value;
    }

    /**
     * Gets the value of the authRealm property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the authRealm property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAuthRealm().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link AuthRealm }
     */
    public List<AuthRealm> getAuthRealm() {
        return this.authRealm;
    }

    /**
     * Gets the value of the jaccProvider property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the jaccProvider property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJaccProvider().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link JaccProvider }
     */
    public List<JaccProvider> getJaccProvider() {
        return this.jaccProvider;
    }

    /**
     * Gets the value of the auditModule property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the auditModule property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAuditModule().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link AuditModule }
     */
    public List<AuditModule> getAuditModule() {
        return this.auditModule;
    }

    /**
     * Gets the value of the messageSecurityConfig property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the messageSecurityConfig property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMessageSecurityConfig().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link MessageSecurityConfig }
     */
    public List<MessageSecurityConfig> getMessageSecurityConfig() {
        return this.messageSecurityConfig;
    }

    /**
     * Gets the value of the property property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the property property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProperty().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link Property }
     */
    public List<Property> getProperty() {
        return this.property;
    }

    public void addVetoableChangeListener(VetoableChangeListener param0) {
        support.addVetoableChangeListener(param0);
    }

    public void addVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.addVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.removeVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(VetoableChangeListener param0) {
        support.removeVetoableChangeListener(param0);
    }

}
