//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-04/12/2007 12:08 AM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.24 at 01:25:15 PM PDT 
//


package com.sun.enterprise.config.serverbeans;

import org.jvnet.hk2.config.Attribute;
import org.jvnet.hk2.config.Configured;
import org.jvnet.hk2.config.Element;

import java.beans.PropertyVetoException;
import java.beans.VetoableChangeListener;
import java.beans.VetoableChangeSupport;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 *
 */

/* @XmlType(name = "", propOrder = {
    "principalOrUserGroup",
    "backendPrincipal"
}) */
@Configured
public class SecurityMap
        implements Serializable {

	final transient private VetoableChangeSupport support = new VetoableChangeSupport(this);

    private final static long serialVersionUID = 1L;
    @Attribute(required = true)

    protected String name;

    @Element
    List<String> principal = new ConstrainedList<String>("principal = new ArrayList<String>()", support);

    @Element
    List<String> userGroup  = new ConstrainedList<String>("userGroup = new ArrayList<String>()", support);

    @Element(required=true)
    protected BackendPrincipal backendPrincipal;
    


    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
        try {
            support.fireVetoableChange("name", this.name, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.name = value;
    }

    public void addPrincipal(String principal) {
        this.principal.add(principal);
    }

    public List<String>  getPrincipal() {
        return principal;
    }

    public void addUserGroup(String userGroup) {          
        this.userGroup.add(userGroup);
    }

    public List<String>  getUserGroup() {
        return userGroup;
    }


    /**
     * Backward compatibility API
     */
    public List<String> getPrincipalOrUserGroup() {
        List<String> bag = new ArrayList<String>();
        bag.addAll(principal);
        bag.addAll(userGroup);
        return bag;
    }

    /**
     * Gets the value of the backendPrincipal property.
     *
     * @return possible object is
     *         {@link BackendPrincipal }
     */
    public BackendPrincipal getBackendPrincipal() {
        return backendPrincipal;
    }

    /**
     * Sets the value of the backendPrincipal property.
     *
     * @param value allowed object is
     *              {@link BackendPrincipal }
     */
    public void setBackendPrincipal(BackendPrincipal value) {
        try {
            support.fireVetoableChange("backendPrincipal", this.backendPrincipal, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.backendPrincipal = value;
    }

    public void addVetoableChangeListener(VetoableChangeListener param0) {
        support.addVetoableChangeListener(param0);
    }

    public void addVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.addVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.removeVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(VetoableChangeListener param0) {
        support.removeVetoableChangeListener(param0);
    }

}
