//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-04/12/2007 12:08 AM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.24 at 01:25:15 PM PDT 
//


package com.sun.enterprise.config.serverbeans;

import org.jvnet.hk2.config.Attribute;
import org.jvnet.hk2.config.Configured;
import org.jvnet.hk2.config.Element;

import java.beans.PropertyVetoException;
import java.beans.VetoableChangeListener;
import java.beans.VetoableChangeSupport;
import java.io.Serializable;


/**
 *
 */

/* @XmlType(name = "", propOrder = {
    "healthChecker"
}) */
@Configured
public class ServerRef implements Ref, Serializable {

    final transient private VetoableChangeSupport support = new VetoableChangeSupport(this);
    
    private final static long serialVersionUID = 1L;
    @Attribute(required = true)

    protected String ref;
    @Attribute

    protected String disableTimeoutInMinutes;
    @Attribute

    protected String lbEnabled;
    @Attribute

    protected String enabled;
    @Element
    protected HealthChecker healthChecker;



    /**
     * Gets the value of the ref property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getRef() {
        return ref;
    }

    /**
     * Sets the value of the ref property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRef(String value) {
        try {
            support.fireVetoableChange("ref", this.ref, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.ref = value;
    }

    /**
     * Gets the value of the disableTimeoutInMinutes property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getDisableTimeoutInMinutes() {
        if (disableTimeoutInMinutes == null) {
            return "30";
        } else {
            return disableTimeoutInMinutes;
        }
    }

    /**
     * Sets the value of the disableTimeoutInMinutes property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDisableTimeoutInMinutes(String value) {
        try {
            support.fireVetoableChange("disableTimeoutInMinutes", this.disableTimeoutInMinutes, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.disableTimeoutInMinutes = value;
    }

    /**
     * Gets the value of the lbEnabled property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getLbEnabled() {
        if (lbEnabled == null) {
            return "false";
        } else {
            return lbEnabled;
        }
    }

    /**
     * Sets the value of the lbEnabled property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLbEnabled(String value) {
        try {
            support.fireVetoableChange("lbEnabled", this.lbEnabled, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.lbEnabled = value;
    }

    /**
     * Gets the value of the enabled property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getEnabled() {
        if (enabled == null) {
            return "true";
        } else {
            return enabled;
        }
    }

    /**
     * Sets the value of the enabled property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setEnabled(String value) {
        try {
            support.fireVetoableChange("enabled", this.enabled, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.enabled = value;
    }

    /**
     * Gets the value of the healthChecker property.
     *
     * @return possible object is
     *         {@link HealthChecker }
     */
    public HealthChecker getHealthChecker() {
        return healthChecker;
    }

    /**
     * Sets the value of the healthChecker property.
     *
     * @param value allowed object is
     *              {@link HealthChecker }
     */
    public void setHealthChecker(HealthChecker value) {
        try {
            support.fireVetoableChange("healthChecker", this.healthChecker, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.healthChecker = value;
    }

    public void addVetoableChangeListener(VetoableChangeListener param0) {
        support.addVetoableChangeListener(param0);
    }

    public void addVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.addVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.removeVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(VetoableChangeListener param0) {
        support.removeVetoableChangeListener(param0);
    }

}
