//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-04/12/2007 12:08 AM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.24 at 01:25:15 PM PDT 
//


package com.sun.enterprise.config.serverbeans;

import org.jvnet.hk2.config.Configured;
import org.jvnet.hk2.config.Element;

import java.beans.PropertyVetoException;
import java.beans.VetoableChangeListener;
import java.beans.VetoableChangeSupport;
import java.io.Serializable;


/**
 *
 */

/* @XmlType(name = "", propOrder = {
    "sessionManager",
    "sessionProperties"
}) */
@Configured
public class SessionConfig
        implements Serializable {

	final transient private VetoableChangeSupport support = new VetoableChangeSupport(this);

    private final static long serialVersionUID = 1L;
    @Element
    protected SessionManager sessionManager;
    @Element
    protected SessionProperties sessionProperties;



    /**
     * Gets the value of the sessionManager property.
     *
     * @return possible object is
     *         {@link SessionManager }
     */
    public SessionManager getSessionManager() {
        return sessionManager;
    }

    /**
     * Sets the value of the sessionManager property.
     *
     * @param value allowed object is
     *              {@link SessionManager }
     */
    public void setSessionManager(SessionManager value) {
        try {
            support.fireVetoableChange("sessionManager", this.sessionManager, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.sessionManager = value;
    }

    /**
     * Gets the value of the sessionProperties property.
     *
     * @return possible object is
     *         {@link SessionProperties }
     */
    public SessionProperties getSessionProperties() {
        return sessionProperties;
    }

    /**
     * Sets the value of the sessionProperties property.
     *
     * @param value allowed object is
     *              {@link SessionProperties }
     */
    public void setSessionProperties(SessionProperties value) {
        try {
            support.fireVetoableChange("sessionProperties", this.sessionProperties, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.sessionProperties = value;
    }

    public void addVetoableChangeListener(VetoableChangeListener param0) {
        support.addVetoableChangeListener(param0);
    }

    public void addVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.addVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.removeVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(VetoableChangeListener param0) {
        support.removeVetoableChangeListener(param0);
    }

}
