//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-04/12/2007 12:08 AM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.24 at 01:25:15 PM PDT 
//


package com.sun.enterprise.config.serverbeans;

import org.jvnet.hk2.config.Attribute;
import org.jvnet.hk2.config.Configured;

import java.beans.PropertyVetoException;
import java.beans.VetoableChangeListener;
import java.beans.VetoableChangeSupport;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 *
 */

/* @XmlType(name = "", propOrder = {
    "property"
}) */
@Configured
public class TransactionService
        implements Serializable {

	final transient private VetoableChangeSupport support = new VetoableChangeSupport(this);

    private final static long serialVersionUID = 1L;
    @Attribute

    protected String automaticRecovery;
    @Attribute

    protected String timeoutInSeconds;
    @Attribute

    protected String txLogDir;
    @Attribute

    protected String heuristicDecision;
    @Attribute

    protected String retryTimeoutInSeconds;
    @Attribute

    protected String keypointInterval;
    protected List<Property> property = new ConstrainedList<Property>("property", support);



    /**
     * Gets the value of the automaticRecovery property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getAutomaticRecovery() {
        if (automaticRecovery == null) {
            return "false";
        } else {
            return automaticRecovery;
        }
    }

    /**
     * Sets the value of the automaticRecovery property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAutomaticRecovery(String value) {
        try {
            support.fireVetoableChange("automaticRecovery", this.automaticRecovery, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.automaticRecovery = value;
    }

    /**
     * Gets the value of the timeoutInSeconds property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getTimeoutInSeconds() {
        if (timeoutInSeconds == null) {
            return "0";
        } else {
            return timeoutInSeconds;
        }
    }

    /**
     * Sets the value of the timeoutInSeconds property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTimeoutInSeconds(String value) {
        try {
            support.fireVetoableChange("timeoutInSeconds", this.timeoutInSeconds, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.timeoutInSeconds = value;
    }

    /**
     * Gets the value of the txLogDir property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getTxLogDir() {
        return txLogDir;
    }

    /**
     * Sets the value of the txLogDir property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTxLogDir(String value) {
        try {
            support.fireVetoableChange("txLogDir", this.txLogDir, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.txLogDir = value;
    }

    /**
     * Gets the value of the heuristicDecision property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getHeuristicDecision() {
        if (heuristicDecision == null) {
            return "rollback";
        } else {
            return heuristicDecision;
        }
    }

    /**
     * Sets the value of the heuristicDecision property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setHeuristicDecision(String value) {
        try {
            support.fireVetoableChange("heuristicDecision", this.heuristicDecision, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.heuristicDecision = value;
    }

    /**
     * Gets the value of the retryTimeoutInSeconds property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getRetryTimeoutInSeconds() {
        if (retryTimeoutInSeconds == null) {
            return "600";
        } else {
            return retryTimeoutInSeconds;
        }
    }

    /**
     * Sets the value of the retryTimeoutInSeconds property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRetryTimeoutInSeconds(String value) {
        try {
            support.fireVetoableChange("retryTimeoutInSeconds", this.retryTimeoutInSeconds, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.retryTimeoutInSeconds = value;
    }

    /**
     * Gets the value of the keypointInterval property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getKeypointInterval() {
        if (keypointInterval == null) {
            return "2048";
        } else {
            return keypointInterval;
        }
    }

    /**
     * Sets the value of the keypointInterval property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setKeypointInterval(String value) {
        try {
            support.fireVetoableChange("keypointInterval", this.keypointInterval, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.keypointInterval = value;
    }

    /**
     * Gets the value of the property property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the property property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProperty().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link Property }
     */
    public List<Property> getProperty() {
        return this.property;
    }

    public void addVetoableChangeListener(VetoableChangeListener param0) {
        support.addVetoableChangeListener(param0);
    }

    public void addVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.addVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.removeVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(VetoableChangeListener param0) {
        support.removeVetoableChangeListener(param0);
    }

}
