//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-04/12/2007 12:08 AM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.24 at 01:25:15 PM PDT 
//


package com.sun.enterprise.config.serverbeans;

import org.jvnet.hk2.config.Attribute;
import org.jvnet.hk2.config.Configured;
import org.jvnet.hk2.config.Element;

import java.beans.PropertyVetoException;
import java.beans.VetoableChangeListener;
import java.beans.VetoableChangeSupport;
import java.io.Serializable;
import java.util.List;


/**
 *
 */

/* @XmlType(name = "", propOrder = {
    "httpAccessLog",
    "property"
}) */
@Configured
public class VirtualServer
        implements Serializable {

	final transient private VetoableChangeSupport support = new VetoableChangeSupport(this);

    private final static long serialVersionUID = 1L;
    @Attribute(required = true)

    protected String id;
    @Attribute

    protected String httpListeners;
    @Attribute

    protected String defaultWebModule;
    @Attribute(required = true)

    protected String hosts;
    @Attribute

    protected String state;
    @Attribute

    protected String docroot;
    @Attribute

    protected String logFile;
    @Element
    protected HttpAccessLog httpAccessLog;

    @Element
    protected List<Property> property = new ConstrainedList<Property>("property", support);



    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setId(String value) {
        try {
            support.fireVetoableChange("id", this.id, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.id = value;
    }

    /**
     * Gets the value of the httpListeners property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getHttpListeners() {
        return httpListeners;
    }

    /**
     * Sets the value of the httpListeners property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setHttpListeners(String value) {
        try {
            support.fireVetoableChange("httpListeners", this.httpListeners, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.httpListeners = value;
    }

    /**
     * Gets the value of the defaultWebModule property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getDefaultWebModule() {
        return defaultWebModule;
    }

    /**
     * Sets the value of the defaultWebModule property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDefaultWebModule(String value) {
        try {
            support.fireVetoableChange("defaultWebModule", this.defaultWebModule, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.defaultWebModule = value;
    }

    /**
     * Gets the value of the hosts property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getHosts() {
        return hosts;
    }

    /**
     * Sets the value of the hosts property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setHosts(String value) {
        try {
            support.fireVetoableChange("hosts", this.hosts, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.hosts = value;
    }

    /**
     * Gets the value of the state property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getState() {
        if (state == null) {
            return "on";
        } else {
            return state;
        }
    }

    /**
     * Sets the value of the state property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setState(String value) {
        try {
            support.fireVetoableChange("state", this.state, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.state = value;
    }

    /**
     * Gets the value of the docroot property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getDocroot() {
        return docroot;
    }

    /**
     * Sets the value of the docroot property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDocroot(String value) {
        try {
            support.fireVetoableChange("docroot", this.docroot, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.docroot = value;
    }

    /**
     * Gets the value of the logFile property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getLogFile() {
        if (logFile == null) {
            return "${com.sun.aas.instanceRoot}/logs/server.log";
        } else {
            return logFile;
        }
    }

    /**
     * Sets the value of the logFile property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLogFile(String value) {
        try {
            support.fireVetoableChange("logFile", this.logFile, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.logFile = value;
    }

    /**
     * Gets the value of the httpAccessLog property.
     *
     * @return possible object is
     *         {@link HttpAccessLog }
     */
    public HttpAccessLog getHttpAccessLog() {
        return httpAccessLog;
    }

    /**
     * Sets the value of the httpAccessLog property.
     *
     * @param value allowed object is
     *              {@link HttpAccessLog }
     */
    public void setHttpAccessLog(HttpAccessLog value) {
        try {
            support.fireVetoableChange("httpAccessLog", this.httpAccessLog, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.httpAccessLog = value;
    }

    /**
     * Gets the value of the property property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the property property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProperty().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link Property }
     */
    public List<Property> getProperty() {
        return this.property;
    }

    public void addVetoableChangeListener(VetoableChangeListener param0) {
        support.addVetoableChangeListener(param0);
    }

    public void addVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.addVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.removeVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(VetoableChangeListener param0) {
        support.removeVetoableChangeListener(param0);
    }

}
