//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-04/12/2007 12:08 AM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.24 at 01:25:15 PM PDT 
//


package com.sun.enterprise.config.serverbeans;

import org.jvnet.hk2.config.Attribute;
import org.jvnet.hk2.config.Configured;

import java.beans.PropertyVetoException;
import java.beans.VetoableChangeListener;
import java.beans.VetoableChangeSupport;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 *
 */

/* @XmlType(name = "", propOrder = {
    "property"
}) */
@Configured
public class WebContainerAvailability
        implements Serializable {

	final transient private VetoableChangeSupport support = new VetoableChangeSupport(this);

    private final static long serialVersionUID = 1L;
    @Attribute

    protected String availabilityEnabled;
    @Attribute

    protected String persistenceType;
    @Attribute

    protected String persistenceFrequency;
    @Attribute

    protected String persistenceScope;
    @Attribute

    protected String persistenceStoreHealthCheckEnabled;
    @Attribute

    protected String ssoFailoverEnabled;
    @Attribute

    protected String httpSessionStorePoolName;
    protected List<Property> property = new ConstrainedList<Property>("property", support);



    /**
     * Gets the value of the availabilityEnabled property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getAvailabilityEnabled() {
        return availabilityEnabled;
    }

    /**
     * Sets the value of the availabilityEnabled property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAvailabilityEnabled(String value) {
        try {
            support.fireVetoableChange("availabilityEnabled", this.availabilityEnabled, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.availabilityEnabled = value;
    }

    /**
     * Gets the value of the persistenceType property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getPersistenceType() {
        if (persistenceType == null) {
            return "memory";
        } else {
            return persistenceType;
        }
    }

    /**
     * Sets the value of the persistenceType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPersistenceType(String value) {
        try {
            support.fireVetoableChange("persistenceType", this.persistenceType, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.persistenceType = value;
    }

    /**
     * Gets the value of the persistenceFrequency property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getPersistenceFrequency() {
        return persistenceFrequency;
    }

    /**
     * Sets the value of the persistenceFrequency property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPersistenceFrequency(String value) {
        try {
            support.fireVetoableChange("persistenceFrequency", this.persistenceFrequency, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.persistenceFrequency = value;
    }

    /**
     * Gets the value of the persistenceScope property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getPersistenceScope() {
        return persistenceScope;
    }

    /**
     * Sets the value of the persistenceScope property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPersistenceScope(String value) {
        try {
            support.fireVetoableChange("persistenceScope", this.persistenceScope, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.persistenceScope = value;
    }

    /**
     * Gets the value of the persistenceStoreHealthCheckEnabled property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getPersistenceStoreHealthCheckEnabled() {
        if (persistenceStoreHealthCheckEnabled == null) {
            return "false";
        } else {
            return persistenceStoreHealthCheckEnabled;
        }
    }

    /**
     * Sets the value of the persistenceStoreHealthCheckEnabled property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPersistenceStoreHealthCheckEnabled(String value) {
        try {
            support.fireVetoableChange("persistenceStoreHealthCheckEnabled", this.persistenceStoreHealthCheckEnabled, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.persistenceStoreHealthCheckEnabled = value;
    }

    /**
     * Gets the value of the ssoFailoverEnabled property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getSsoFailoverEnabled() {
        if (ssoFailoverEnabled == null) {
            return "false";
        } else {
            return ssoFailoverEnabled;
        }
    }

    /**
     * Sets the value of the ssoFailoverEnabled property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSsoFailoverEnabled(String value) {
        try {
            support.fireVetoableChange("ssoFailoverEnabled", this.ssoFailoverEnabled, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.ssoFailoverEnabled = value;
    }

    /**
     * Gets the value of the httpSessionStorePoolName property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getHttpSessionStorePoolName() {
        return httpSessionStorePoolName;
    }

    /**
     * Sets the value of the httpSessionStorePoolName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setHttpSessionStorePoolName(String value) {
        try {
            support.fireVetoableChange("httpSessionStorePoolName", this.httpSessionStorePoolName, value);
        } catch (PropertyVetoException _x) {
            return;
        }
        this.httpSessionStorePoolName = value;
    }

    /**
     * Gets the value of the property property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the property property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProperty().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link Property }
     */
    public List<Property> getProperty() {
        return this.property;
    }

    public void addVetoableChangeListener(VetoableChangeListener param0) {
        support.addVetoableChangeListener(param0);
    }

    public void addVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.addVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(String param0, VetoableChangeListener param1) {
        support.removeVetoableChangeListener(param0, param1);
    }

    public void removeVetoableChangeListener(VetoableChangeListener param0) {
        support.removeVetoableChangeListener(param0);
    }

}
