#!/bin/bash
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# Copyright (c) 2010-2014 Oracle and/or its affiliates. All rights reserved.
#
# The contents of this file are subject to the terms of either the GNU
# General Public License Version 2 only ("GPL") or the Common Development
# and Distribution License("CDDL") (collectively, the "License").  You
# may not use this file except in compliance with the License.  You can
# obtain a copy of the License at
# https://glassfish.dev.java.net/public/CDDL+GPL_1_1.html
# or packager/legal/LICENSE.txt.  See the License for the specific
# language governing permissions and limitations under the License.
#
# When distributing the software, include this License Header Notice in each
# file and include the License file at packager/legal/LICENSE.txt.
#
# GPL Classpath Exception:
# Oracle designates this particular file as subject to the "Classpath"
# exception as provided by Oracle in the GPL Version 2 section of the License
# file that accompanied this code.
#
# Modifications:
# If applicable, add the following below the License Header, with the fields
# enclosed by brackets [] replaced by your own identifying information:
# "Portions Copyright [year] [name of copyright owner]"
#
# Contributor(s):
# If you wish your version of this file to be governed by only the CDDL or
# only the GPL Version 2, indicate your decision by adding "[Contributor]
# elects to include this software in this distribution under the [CDDL or GPL
# Version 2] license."  If you don't indicate a single choice of license, a
# recipient has the option to distribute your version of this file under
# either the CDDL, the GPL Version 2 or to extend the choice of license to
# its licensees as provided above.  However, if you add GPL Version 2 code
# and therefore, elected the GPL Version 2 license, then the option applies
# only if the new code is made subject to such option by the copyright
# holder.
#

#
# Count the number of errors in each findbugsXml.xml file.
#
# Usage: fbcount [-i xml-file-list] [-v]
#	-i file	get list of findbugsXml.xml files from file
#	-v	verbose
#

TOOLS=/net/gf-hudson/scratch/gf-hudson/export2/hudson/tools/findbugs-tool-latest
FINDBUGSTOTEXT=$TOOLS/FindbugsToText.jar
PATH=$TOOLS:$PATH

USAGE="fbcount [-i xml-file-list] [-v]"
fblist=
e=true

while getopts :i:v i
do
	case $i in
	i)	fblist=$OPTARG;;
	v)	e=echo;;
	'?')	echo "$USAGE"; exit 2;;
	esac
done
shift `expr $OPTIND - 1`

until [ -f pom.xml -o -f build.gradle -o . -ef / -o . -ef "$HOME" ]
do
	cd ..
done

# choose the correct FindBugs XML file name if we're using gradle
if [ -f build.gradle ]
then
	XMLNAME=main.xml
else
	XMLNAME=findbugsXml.xml
fi

if [ -n "$WORK_DIR" -a -n "$DEV_ROOT" ]
then
	case "$PWD" in
	$DEV_ROOT/mod*)
		# convert source directory name to build directory name
		mod=${PWD#$DEV_ROOT/mod}
		cd "${WORK_DIR}/$mod"
		;;
	${WORK_DIR}*)
		# in the right place, just stay here
		;;
	*)
		# don't know where we are, go to the work directory
		cd "$WORK_DIR"
		;;
	esac
fi

#MAVEN_OPTS=-Xmx512m mvn findbugs:findbugs
(
if [ -n "$fblist" ]
then
	cat "$fblist"
else
	find [a-z]* -xdev -name .svn -prune -o -name .m2 -prune \
		-o -name "$XMLNAME" -print
fi
) | \
while read file
do
	$e "Process errors in $file..."
	dir=`dirname "$file"`
	pdir=`dirname "$dir"`
	mod=$pdir
	if [ -n "$WORK_DIR" -a -n "$DEV_ROOT" ]
	then
		dir="$PWD/$pdir"
		mod=${dir#$WORK_DIR/}
		pdir="mod/$mod"	# relative to $DEV_ROOT
	fi
	$e "Directory: $pdir"
	cnt=`java -jar $FINDBUGSTOTEXT < "$file" | wc -l`
	echo "$mod	$cnt"
done
