#! /bin/sh
#
# fbpost - post FindBugs errors to a servlet that stores them in a database
#
#	Usage: fbpost timestamp project START|END|email [err]
#
MAILPROG=${MAILPROG:-/bin/mailx}
OWNER="jill.sato@oracle.com,art.rofrano@oracle.com"

# Art's prog to archive data.
if java PostFindBugsErrors "$@"
then
	exit 0 # success
else
	echo fbpost "$@" | \
	$MAILPROG -s "FindBugs Data Post Error" "$OWNER"
	exit 1
fi
