#!/bin/sh  
#
# findbugsmail - collect FindBugs errors and generate email to the owners
#
#	-n		- don't send mail, show what would be sent
#	-h		- high priority errors; log to database
#	-o email	- set owner email address for error notifications
#	-e email	- force error email to this address
#	-p project	- set project name for email header and log message
#	-v		- verbose; show what's happening
#

OWNER="jill.sato@oracle.com,romain.grecourt@oracle.com,shannon@java.net,neil.kenig@oracle.com"

USAGE='findbugsmail [-n] [-h] [-o owner-email] [-e email] [-p project] [-v]'
VERBOSE=":"
TEE=cat
LOG=false
PROJECT=UNKNOWN

while getopts :nho:e:p:v i
do
	case $i in
	n)	FBNARGS="$FBNARGS -n";;
	h)	FBNARGS="$FBNARGS -h"; LOG=true;;
	o)	FBNARGS="$FBNARGS -o \"$OPTARG\""; OWNER="$OPTARG";;
	e)	FBNARGS="$FBNARGS -e \"$OPTARG\"";;
	p)	FBNARGS="$FBNARGS -p \"$OPTARG\""; PROJECT="$OPTARG";;
	v)	VERBOSE=echo; TEE="tee /dev/stderr"; FBNARGS="$FBNARGS -v";;
	'?')	echo "$USAGE"; exit 2;;
	esac
done
shift `expr $OPTIND - 1`

if [ $# -eq 0  ]; then
	ws_dir=`pwd`
else
	ws_dir=$1
fi
cd `dirname "$0"`
script_dir=`pwd`	# get absolute path

$VERBOSE "Workspace directory: $ws_dir" >&2
$VERBOSE "Script directory: $script_dir" >&2

TIMESTAMP=`date +%Y%m%d%H%M%S`
if $LOG
then
	$VERBOSE "LOG: $TIMESTAMP: $PROJECT: START"
	(cd $script_dir; fbpost "$TIMESTAMP" "$PROJECT" START)
fi
cd $ws_dir
find [a-z]* -xdev -name .svn -prune -o -name .m2 -prune \
	-o -name findbugsXml.xml -print | \
while read file
do
	$VERBOSE "Processing file: $file" >&2
	dir=`dirname "$file"`
	pdir=`dirname "$dir"`
	java -jar $script_dir/FindbugsToText.jar < "$file" | \
		sed -e "s;^;$pdir/src/main/java/;" | \
		$script_dir/svnowner
done | $TEE | \
(cd $script_dir; eval ./fbnag -T "$TIMESTAMP" $FBNARGS)
if $LOG
then
	$VERBOSE "LOG: $TIMESTAMP: $PROJECT: END"
	(cd $script_dir; fbpost "$TIMESTAMP" "$PROJECT" END)
fi
exit 0
