#!/bin/sh  
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# Copyright (c) 2010-2013 Oracle and/or its affiliates. All rights reserved.
#
# The contents of this file are subject to the terms of either the GNU
# General Public License Version 2 only ("GPL") or the Common Development
# and Distribution License("CDDL") (collectively, the "License").  You
# may not use this file except in compliance with the License.  You can
# obtain a copy of the License at
# https://glassfish.dev.java.net/public/CDDL+GPL_1_1.html
# or packager/legal/LICENSE.txt.  See the License for the specific
# language governing permissions and limitations under the License.
#
# When distributing the software, include this License Header Notice in each
# file and include the License file at packager/legal/LICENSE.txt.
#
# GPL Classpath Exception:
# Oracle designates this particular file as subject to the "Classpath"
# exception as provided by Oracle in the GPL Version 2 section of the License
# file that accompanied this code.
#
# Modifications:
# If applicable, add the following below the License Header, with the fields
# enclosed by brackets [] replaced by your own identifying information:
# "Portions Copyright [year] [name of copyright owner]"
#
# Contributor(s):
# If you wish your version of this file to be governed by only the CDDL or
# only the GPL Version 2, indicate your decision by adding "[Contributor]
# elects to include this software in this distribution under the [CDDL or GPL
# Version 2] license."  If you don't indicate a single choice of license, a
# recipient has the option to distribute your version of this file under
# either the CDDL, the GPL Version 2 or to extend the choice of license to
# its licensees as provided above.  However, if you add GPL Version 2 code
# and therefore, elected the GPL Version 2 license, then the option applies
# only if the new code is made subject to such option by the copyright
# holder.
#

#
# findbugsmail - collect FindBugs errors and generate email to the owners
#
#	-n		- don't send mail, show what would be sent
#	-h		- high priority errors; log to database
#	-o email	- set owner email address for error notifications
#	-e email	- force error email to this address
#	-p project	- set project name for email header and log message
#	-v		- verbose; show what's happening
#

OWNER="jill.sato@oracle.com,romain.grecourt@oracle.com,bill.shannon@oracle.com,ed.bratt@oracle.com"

USAGE='findbugsmail [-n] [-h] [-o owner-email] [-e email] [-p project] [-v]'
VERBOSE=":"
TEE=cat
LOG=false
PROJECT=UNKNOWN

while getopts :nho:e:p:v i
do
	case $i in
	n)	FBNARGS="$FBNARGS -n";;
	h)	FBNARGS="$FBNARGS -h"; LOG=true;;
	o)	FBNARGS="$FBNARGS -o \"$OPTARG\""; OWNER="$OPTARG";;
	e)	FBNARGS="$FBNARGS -e \"$OPTARG\"";;
	p)	FBNARGS="$FBNARGS -p \"$OPTARG\""; PROJECT="$OPTARG";;
	v)	VERBOSE=echo; TEE="tee /dev/stderr"; FBNARGS="$FBNARGS -v";;
	'?')	echo "$USAGE"; exit 2;;
	esac
done
shift `expr $OPTIND - 1`

if [ $# -eq 0  ]; then
	ws_dir=`pwd`
else
	ws_dir=$1
fi
cd `dirname "$0"`
script_dir=`pwd`	# get absolute path

$VERBOSE "Workspace directory: $ws_dir" >&2
$VERBOSE "Script directory: $script_dir" >&2

TIMESTAMP=`date +%Y%m%d%H%M%S`
if $LOG
then
	$VERBOSE "LOG: $TIMESTAMP: $PROJECT: START"
	(cd $script_dir; fbpost "$TIMESTAMP" "$PROJECT" START)
fi
cd $ws_dir
REV=`scmrev`
find [a-z]* -xdev -name .svn -prune -o -name .m2 -prune \
	-name .git -prune -o -name .hg -prune \
	-o -name findbugsXml.xml -print | \
while read file
do
	$VERBOSE "Processing file: $file" >&2
	dir=`dirname "$file"`
	pdir=`dirname "$dir"`
	java -jar $script_dir/FindbugsToText.jar < "$file" | \
		sed -e "s;^;$pdir/src/main/java/;" | \
		$script_dir/scmowner
done | $TEE | \
(cd $script_dir; eval ./fbnag -T "$TIMESTAMP" -r "$REV" $FBNARGS)
if $LOG
then
	$VERBOSE "LOG: $TIMESTAMP: $PROJECT: END"
	(cd $script_dir; fbpost "$TIMESTAMP" "$PROJECT" END)
fi
exit 0
