#!/bin/sh 
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# Copyright (c) 2010-2013 Oracle and/or its affiliates. All rights reserved.
#
# The contents of this file are subject to the terms of either the GNU
# General Public License Version 2 only ("GPL") or the Common Development
# and Distribution License("CDDL") (collectively, the "License").  You
# may not use this file except in compliance with the License.  You can
# obtain a copy of the License at
# https://glassfish.dev.java.net/public/CDDL+GPL_1_1.html
# or packager/legal/LICENSE.txt.  See the License for the specific
# language governing permissions and limitations under the License.
#
# When distributing the software, include this License Header Notice in each
# file and include the License file at packager/legal/LICENSE.txt.
#
# GPL Classpath Exception:
# Oracle designates this particular file as subject to the "Classpath"
# exception as provided by Oracle in the GPL Version 2 section of the License
# file that accompanied this code.
#
# Modifications:
# If applicable, add the following below the License Header, with the fields
# enclosed by brackets [] replaced by your own identifying information:
# "Portions Copyright [year] [name of copyright owner]"
#
# Contributor(s):
# If you wish your version of this file to be governed by only the CDDL or
# only the GPL Version 2, indicate your decision by adding "[Contributor]
# elects to include this software in this distribution under the [CDDL or GPL
# Version 2] license."  If you don't indicate a single choice of license, a
# recipient has the option to distribute your version of this file under
# either the CDDL, the GPL Version 2 or to extend the choice of license to
# its licensees as provided above.  However, if you add GPL Version 2 code
# and therefore, elected the GPL Version 2 license, then the option applies
# only if the new code is made subject to such option by the copyright
# holder.
#

#
# hgowner - convert from line number back to person who last changed that line
#
#	input is of the form "file: line: text",
#	output is of the form "owner: file: line: text".
#
perl -e '

line: while (<>) {
	chop;	# strip newline
	($file, $lineno, $text) = split(/:/, $_, 3);
	if ($file ne $curfile ) {
		$curfile = $file;
		$fileok = 0;
		undef @owners;
		if (-r $file) {
			$st = 
			open(ANN, "hg annotate -u -v $file " .
				"2>/dev/null </dev/null |");
			$i = 1;
			while ($o = <ANN>) {
				chop $o;
				$o =~ s/\s*(.*):.*/\1/;
				if ($o =~ /<.*>/) {
					$o =~ s/.*<(.*)>.*/\1/;
				}
				$owners[$i++] = $o;
			}
			close ANN;
			$fileok = !$?;
		}
	}
	if ($fileok) {
		if ($lineno <= 0 ) { 
			$lineno = 1;
		}
		$owner = $owners[$lineno];
	} else {
		$owner =  "UNKNOWN";
	}
        
	printf "%s: %s\n", $owner, $_;
}
'
