#!/bin/bash 
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# Copyright (c) 2013-2014 Oracle and/or its affiliates. All rights reserved.
#
# The contents of this file are subject to the terms of either the GNU
# General Public License Version 2 only ("GPL") or the Common Development
# and Distribution License("CDDL") (collectively, the "License").  You
# may not use this file except in compliance with the License.  You can
# obtain a copy of the License at
# https://glassfish.dev.java.net/public/CDDL+GPL_1_1.html
# or packager/legal/LICENSE.txt.  See the License for the specific
# language governing permissions and limitations under the License.
#
# When distributing the software, include this License Header Notice in each
# file and include the License file at packager/legal/LICENSE.txt.
#
# GPL Classpath Exception:
# Oracle designates this particular file as subject to the "Classpath"
# exception as provided by Oracle in the GPL Version 2 section of the License
# file that accompanied this code.
#
# Modifications:
# If applicable, add the following below the License Header, with the fields
# enclosed by brackets [] replaced by your own identifying information:
# "Portions Copyright [year] [name of copyright owner]"
#
# Contributor(s):
# If you wish your version of this file to be governed by only the CDDL or
# only the GPL Version 2, indicate your decision by adding "[Contributor]
# elects to include this software in this distribution under the [CDDL or GPL
# Version 2] license."  If you don't indicate a single choice of license, a
# recipient has the option to distribute your version of this file under
# either the CDDL, the GPL Version 2 or to extend the choice of license to
# its licensees as provided above.  However, if you add GPL Version 2 code
# and therefore, elected the GPL Version 2 license, then the option applies
# only if the new code is made subject to such option by the copyright
# holder.
#

#
# scmrev - show most recent revision
#
# determines the SCM system in use and calls the corresponding script
#

# determine if directory is a p4 workspace
isp4ws() {
	if [ -n "$P4CONFIG" ]
	then
		if [ -f "$1/$P4CONFIG" ]
		then
			return 0
		else
			return 1
		fi
	elif [ -n "$P4PORT" ]
	then
		root=`p4 client -o | awk '/^Root:$/ { print $2; }'`
		case $1 in
		$root|$root/*)	return 0;;
		esac
		return 1
	else
		return 1
	fi
}

p=$PWD
while :
do
	if [ -d .svn ]
	then
		scm=svn
		break
	elif [ -d .hg ]
	then
		scm=hg
		break
	elif [ -d .git ]
	then
		scm=git
		break
	elif isp4ws $PWD
	then
		scm=p4
		break
	fi
	if [ . -ef / -o . -ef "$HOME" ]
	then
		echo "scmrev: can't determine SCM system"
		exit 1
	fi
	cd ..
done
cd $p
exec ${scm}rev "$@"
